### ISSUE TITLE
impl_name: create_runtime_str!("demo-node"),

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-node-template#10]
in this tutorial https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain  
it says:

> you can see at the top of the Substrate UI that the Runtime will have our updated name!

which will not happen with the suggested "[complete version of this file](https://github.com/substrate-developer-hub/substrate-package/blob/8d319c899395f6935a9b95250660f8b28f578a2a/substrate-node-template/runtime/src/lib.rs)" 

![Screenshot from 2019-11-17 10-56-05](https://user-images.githubusercontent.com/7796035/69005988-9d902480-0929-11ea-8ac2-0b65775b4546.png)

unless you change these lines

https://github.com/substrate-developer-hub/substrate-package/blob/8d319c899395f6935a9b95250660f8b28f578a2a/substrate-node-template/runtime/src/lib.rs#L94-L95

to something different:

```rust
	spec_name: create_runtime_str!("DEMO"),
	impl_name: create_runtime_str!("DEMO-node"),
```
then the top will look like this:

![Screenshot from 2019-11-17 11-00-27](https://user-images.githubusercontent.com/7796035/69005995-a5e85f80-0929-11ea-9afc-46199de19d42.png)

**Comment by drandreaskrueger** [comment]
P.S.: This and the previous 2 issues are really tiny things; still, why not report them?

I got it all working! Great tutorial. Thank you very much.

**Comment by riusricardo** [comment]
Closing because it will be deprecated soon.

**Comment by drandreaskrueger** [comment]
Ooops. so I have wasted my time there? Very sorry.

Can you please give me a list of tutorials which are worth learning now?

**Comment by riusricardo** [comment]
It is not wasted time ;) you got the basics for building on Substrate :1st_place_medal: 
Substrate is evolving very fast and we are very close to launch Substrate 2.0.
This tutorial is the only one that will be removed for a more detailed one.

If you try any other tutorial, it should be ok. 
If you want to play with pre-2.0 you may want to try: 
https://github.com/substrate-developer-hub/substrate-proof-of-existence
https://github.com/substrate-developer-hub/substrate-collectables-workshop

Following them directly from GitHub could be challenging but it will give you a better idea of what we want to do.

**Comment by drandreaskrueger** [comment]
Nice one, thanks a lot!
