### ISSUE TITLE
Add a Makefile

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-node-template#102]
**Motivation**

A makefile is a declarative way to describe how to interact with a project such as the Node Template. Adding a makefile will make it easier to interact with this project.

**Suggested Solution**

@xlc has implemented a nice-looking solution https://github.com/xlc/substrate-kitties-2/blob/master/Makefile

**Alternatives**

Cargo build scripts https://doc.rust-lang.org/cargo/reference/build-scripts.html

**Comment by jimmychu0807** [comment]
This can also be implemented with the `scripts` tags in `package.json`. And apparently I don't mind the js ecosystem 😄
