### ISSUE TITLE
Type annotations needed in `sp-arithmetic`

### ISSUE THREAD

**Issue by lamafab** [substrate-developer-hub/substrate-node-template#104]
**Description**

The latest version of this project results in a compilation error.

```bash
  error[E0282]: type annotations needed
      --> /home/anon/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Steps to Reproduce**

```bash
$ git clone https://github.com/substrate-developer-hub/substrate-node-template.git
$ cd substrate-node-template
$ cargo check
```

**Expected vs. Actual Behavior**

It should compile successfully.

**Environment**

- Operating system:
  - `Linux substrate-env 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 GNU/Linux`
- Template version/tag:
  - `master (ad5e2dc)`
- Rust version (run `rustup show`):
  - *tried both:*
    - `rustc 1.47.0 (18bf6b4f0 2020-10-07)`
    - `rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)`

Rustup show:

```bash
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/anon/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2019-09-05-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)

```

**Comment by lamafab** [comment]
Maybe this should be opened in https://github.com/paritytech/substrate ?

**Comment by lamafab** [comment]
As described in https://substrate.dev/docs/en/knowledgebase/getting-started/#rust-nightly-toolchain

> NOTE  Due to a regression in the rust compiler, using the newest rust nightly for compiling the runtime will result in compilation errors. Therefore, it is advised to use the following version until this issue is resolved:

> `rustup install nightly-2020-10-06`

Additionally:

```console
$ rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
```

Closing.

**Comment by wheresaddie** [comment]
yeap @lamafab , let me know if you have any further issues. we are hoping the nightly is resolved ASAP
