### ISSUE TITLE
using canonical Python requests --> {"code":-32700,"message":"Parse error"} 

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-node-template#11]
Perhaps this should be submitted to the main paritytech/substrate repo? Or where else?

# RPC flawed when using Python?

Adapting [this tutorial](https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/) to Python, this -very standard approach- is _not_ working:
```python
payload = {"method": "state_getMetadata", "id":"1", "jsonrpc":"2.0"}
url = "https://dev-node.substrate.dev:9933/"
r = requests.post(url, data=payload, headers = {"Content-Type" : "application/json"})
print (r.status_code, r.text)
```

Have a look at these 3 slightly different attempts:

```
python3 substrate_RPC-flaw.py 
All working on dev-node:  https://dev-node.substrate.dev:9933/ 

Passing a dict as data payload:
payload: {'id': '1', 'method': 'state_getMetadata', 'jsonrpc': '2.0'}
200 {"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}

Turning the dict into a string first:
payload_string: {'id': '1', 'method': 'state_getMetadata', 'jsonrpc': '2.0'}
200 {"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}

Manipulating that string to make substrate happy:
payload_string_manipulated: {"id": "1", "method": "state_getMetadata", "jsonrpc": "2.0"}
200 {'id': '1', 'result': '0x6d65746108601853797374656d01...', 'jsonrpc': '2.0'}
```

THAT took a LONG time to find. Almost proud that I eventually found it ;-)

You can replicate it with this code:

```
import requests # pip install requests

url = "https://dev-node.substrate.dev:9933/"
print ("All working on dev-node: ", url, "\n")

headers = {"Content-Type" : "application/json"}
payload = {"method": "state_getMetadata", "id":"1", "jsonrpc":"2.0"}

print ("Passing a dict as data payload:")
print ("payload:", payload)
r = requests.post(url, data=payload, headers=headers)
print (r.status_code, r.text)

print ("Turning the dict into a string first:")
payload_string = "%s" % payload
print ("payload_string:", payload_string)
r = requests.post(url, data=payload_string, headers=headers)
print (r.status_code, r.text)

print ("Manipulating that string to make substrate happy:")
payload_string_manipulated = payload_string.replace("'", '"')
print ("payload_string_manipulated:", payload_string_manipulated)
r = requests.post(url, data=payload_string_manipulated, headers=headers)
rj = r.json()
rj['result'] = rj['result'][:30] + "..."
print (r.status_code, rj)
```

You need [that library](https://en.wikipedia.org/wiki/Requests_(software)):
```
pip3 install requests
python3 substrate_RPC-flaw.py 
```

**Comment by riusricardo** [comment]
Looks like the tutorial that you are taking a look into could not have the latest changes. It is maintained by @shawntabrizi 
link: https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/

**Comment by riusricardo** [comment]
Have you tried by following the original tutorial?
I would suggest to try it on JavaScript and then see if you can replicate the issue.

**Comment by drandreaskrueger** [comment]
I would suggest you try it out:

    pip3 install requests
    python3 substrate_RPC-flaw.py 

I suppose, it comes from different stringification of dictionaries of JS vs Python??

The substrate RPC server should be language agnostic, and not force people to use JS, no?

Yes, this place HERE might be the wrong place. Where else do you suggest to report this to ?

**Comment by JoshOrndorff** [comment]
The issue is single vs double quotes in the request, not with python vs javascript. I can reproduce your results using `curl`.

```bash
$ curl -H 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_rotateKeys", "id":1 }' https://dev-node.substrate.dev:9933

{"jsonrpc":"2.0","result":"0xb2e193c900159b6cf86b2dedea550030c9c912a160e1996decbd09159527d92f882739012a3bb9803e7ee4ffd72a290436735dbdd20a463db2736365c112597b9a2eca667dedde4a32180b2c6bbecb033cc7640f0683da37f3b070c3f72abb2a","id":1}


$ curl -H 'Content-Type: application/json' --data "{ 'jsonrpc':'2.0', 'method':'author_rotateKeys', 'id':1 }" https://dev-node.substrate.dev:9933

{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
```

Standby and I'll dig deeper.

**Comment by drandreaskrueger** [comment]
> I can reproduce your results using curl.

Oh yes. Of course, that is even simpler. Well done.

It has to do with Python versus Javascript, because (while it's probably different for JS) ... the default way for Python to stringify its dictionaries seems to favor singlequotes '.

While the RPC server is only happy with doublequotes ".

**Comment by JoshOrndorff** [comment]
The documentation for your preferred requests module explains what to do when the RPC you're calling needs valid JSON. https://requests.readthedocs.io/en/latest/user/quickstart/#more-complicated-post-requests (Third code snippet).

**Comment by drandreaskrueger** [comment]
Thanks. So it's like this:

* `r = requests.post(url, data=json.dumps(payload), headers=headers)`

I don't remember to have ever needed to do that, with any request call, ever.  I have just looked up older code ... and found the difference. It was probably because I had always done it like this:

* `r = requests.post(url, json=payload, headers=headers)`

Thank you very much. And sorry to have bothered you with this.
