### ISSUE TITLE
EditorConfig Failed

### ISSUE THREAD

**Issue by chenzongxiong** [substrate-developer-hub/substrate-node-template#111]
I use [editorconfig-checker](https://editorconfig-checker.github.io/#python) to check code style and the configuration of `.editorconfig` is shown as follows,

```
root = true
[*.rs]
indent_style=tab
indent_size=tab
tab_width=4
end_of_line=lf
charset=utf-8
trim_trailing_whitespace=true
# max_line_length=100
max_line_length=120
insert_final_newline=true

[*.yml]
indent_style=space
indent_size=2
tab_width=8
end_of_line=lf

[*.sh]
indent_style=space
indent_size=2
tab_width=8
end_of_line=lf
```

The outputs of `editorconfig-checker` is:
```
└─$ editorconfig-checker
node/src/service.rs:
        298: Wrong indentation type(spaces instead of tabs)
        300: Wrong indentation type(spaces instead of tabs)
        302: Wrong indentation type(spaces instead of tabs)
scripts/init.sh:
        8: Wrong amount of left-padding spaces(want multiple of 2)
        9: Wrong amount of left-padding spaces(want multiple of 2)
        10: Wrong amount of left-padding spaces(want multiple of 2)

6 errors found
```

The source code is at commit 72c1548ec66abcdf935467400d977d5327750ad1. 

I read  [Substrate Code Guide Style](https://github.com/paritytech/substrate/blob/master/docs/STYLE_GUIDE.md) and found that violates the guideline. 

I think it would be nice to keep consistent with guidelines.

**Comment by danforbes** [comment]
Hi, @chenzongxiong - great catch and I absolutely agree we should be consistent! Care to make a PR?
