### ISSUE TITLE
rust build error

### ISSUE THREAD

**Issue by z330789559** [substrate-developer-hub/substrate-node-template#114]
**Description**

Building a Custom Pallet ,
when build dapp，issue
![image](https://user-images.githubusercontent.com/8577836/101238275-1ff8ab80-371a-11eb-8865-52f8e2ad02a1.png)

**Comment by danforbes** [comment]
Have you reviewed the solution to that tutorial? Maybe that will be helpful. https://github.com/substrate-developer-hub/substrate-node-template/blob/tutorials/solutions/build-a-dapp/pallets/template/src/lib.rs It looks like you are missing an import.

**Comment by z330789559** [comment]
I have solved this problem. I need to specify the night version, but I am currently unable to produce blocks. There are also many front-end template bugs. After I finish this project, I can collect the fixed bug questions for you.

**Comment by danforbes** [comment]
Great news, @z330789559 and thank you for the follow up. We can keep this Issue open so you can report back with your findings.

**Comment by NukeManDan** [comment]
@z330789559  and all - https://github.com/substrate-developer-hub/substrate-node-template/releases/tag/v2.0.1 should fix this. If you are willing, please try:

```bash
rustup default stable
# cd  into the substrate-node-template dir
git checkout v2.0.1
git pull
cargo clean # might not be needed...
make init
make build
# get a coffee.... ;) 
```

and see if your build issues on top of a clean clone of the template help. Let us know if not!
