### ISSUE TITLE
Stuck in compilation （make build ）

### ISSUE THREAD

**Issue by wangliqiu2021** [substrate-developer-hub/substrate-node-template#116]
_make build
 WASM_BUILD_TOOLCHAIN=nightly-2020-10-05 cargo build --release
       Compiling node-template-runtime v2.0.0 (`project_dir`/substrate-node-template/runtime)
 Building [=====================================================> ] 857/861: node-template-runtime(build)_

cargo will be stuck here.

**Environment**
 
- Operating system: Ubuntu 20.04
- Template version/tag: v2.0.0
- Rust version (run `rustup show`): 1.48
 
**Additional Information**

_$CARGO_HOME/config.toml:
`
[build]
target-dir = "target"
`
I found the target directory is ~/target and not `project_dir`/target_

So, why?

**Comment by danforbes** [comment]
It seems like there are many good answers to your question here https://stackoverflow.com/questions/65282298/stuck-in-compilation-substrate-node-template-make-build Are there any particular reasons why you're not satisfied with those answers? The node should compile within an hour as long as you are running on fairly modern hardware, do not have any other CPU-intensive processes running at the time, and do not have problems accessing a network in order to download dependencies.

**Comment by wangliqiu2021** [comment]
$CARGO_HOME/config.toml:
if I remove ` [build] target-dir = "target"` this item, `make build ` will succeed.  otherwise `make build ` will get stuck in  `node-template-runtime(build)` this step.

@danforbes

**Comment by bkchr** [comment]
> if I remove ` [build] target-dir = "target"` this item

Why do you add this the config.toml?

**Comment by wangliqiu2021** [comment]
This is the default configuration of cargo. Is there anything wrong with it?
@bkchr

**Comment by bkchr** [comment]
Why do you add this? Just don't add it.

**Comment by danforbes** [comment]
@wangliqiu2021 please delete `$CARGO_HOME/config.toml` and let us know if that solves your problem.

**Comment by wangliqiu2021** [comment]
> @wangliqiu2021 please delete `$CARGO_HOME/config.toml` and let us know if that solves your problem.

Removing `[build] target-dir = "target"` did solve the problem, but I just want to know why adding this option causes the problem.

**Comment by bkchr** [comment]
Because the wasm-builder probably picks this up and cargo locks a target dir. Meaning the normal build is locking the target-dir for the wasm-builder.

I still don't understand why you add this setting. You still did not explained this...
