### ISSUE TITLE
Opaque type have the same definition of non-opaque type

### ISSUE THREAD

**Issue by c410-f3r** [substrate-developer-hub/substrate-node-template#117]
Most of this project is imported from the Substrate repo but I will ask my question here if you guys don't mind.

`Header` type seems to be using to the same types used by the non-opaque exported duplicate.

https://github.com/substrate-developer-hub/substrate-node-template/blob/4d97032c11b8c65936e53a61607d4522d45a29ea/runtime/src/lib.rs#L80

https://github.com/substrate-developer-hub/substrate-node-template/blob/4d97032c11b8c65936e53a61607d4522d45a29ea/runtime/src/lib.rs#L292

Is there a reason for such duplication?

**Comment by danforbes** [comment]
@c410-f3r excellent question - I am not exactly sure. I believe that @expenses may know a bit about this, though...

**Comment by expenses** [comment]
It does have the same definition, but the associated Block type is different. This is a case where it's just simpler to repeat it instead of making things more complicated by trying to deduplicate it.

**Comment by c410-f3r** [comment]
Thanks @danforbes and @expenses 

There are other places with duplications but since it is a intended behavior, I will close this PR.
