### ISSUE TITLE
No tokens/coins after initial build

### ISSUE THREAD

**Issue by TomaszWaszczyk** [substrate-developer-hub/substrate-node-template#119]
**Question**

I have built successfully the node, it works, but I need to make a transfer from Alice to Eve but on the node all people are extremely poor by default ;-(

![image](https://user-images.githubusercontent.com/1605705/102934820-31c1a900-44a5-11eb-9111-66beff94bd55.png)

How to give them some coins? ;-) I need coins/tokens for Alice, how to generate them in some way? How to make brrrrr for Alice :D ?

**Comment by danforbes** [comment]
How are you launching the node? If you use the `--dev` or `--local` flag you should have some accounts prefunded with tokens. You can see this configuration in [the `node/src/chain_spec.rs` file](https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/src/chain_spec.rs).

**Comment by TomaszWaszczyk** [comment]
The node from the course works like a charm, the question (screenshot) comes from the Pathways, I have free time and I want to do as many tasks as possible, maybe there is some difference, hmm currently I just look at the source code line by line and probably in some time I will find why is that. Probably incredible small difference.

;-) Merry Christmas time! (-;

To be honest I do not get the idea why not work only on Substrate repository, big repository, but consistent. I hope will understand it within few days :D generally slowly, but steady.

**Comment by danforbes** [comment]
How are you launching the Pathways node?

**Comment by TomaszWaszczyk** [comment]
Mea culpa (as usual), what I have done:

1. `./target/release/node-template purge-chain --dev`
2. ./target/release/node-template --dev

After `purge-chain` works like a charm (I was lack of purge):

![image](https://user-images.githubusercontent.com/1605705/103046931-37dd8580-458a-11eb-965a-af6ce32eee21.png)

I have sent one coin from Alice to Eve ;-)
