### ISSUE TITLE
Gitpod Integration

### ISSUE THREAD

**Issue by miseenplace** [substrate-developer-hub/substrate-node-template#120]
**Motivation**

Lowering the barrier of entry (devops and time) to tinker with demo code and tutorials.

**Suggested Solution**

The addition of gitpod.yml config file, for the use with gitpod in-browser stateless/ephemeral pre-configured dev environments. Ideally a prebuilt (CI) substrate runtime should be included in the docker image utilized to eliminate lengthy first time compilation.

[Gitpod.io](https://www.gitpod.io/)

**Alternatives**

The devcontainer.json spec works for local and remote container setup, however it is limited to either a local desktop instance of VS-Code application or the platform specific GitHub Codespaces functionality (for in browser ad-hoc use).

Gitpod, is open source, self-hostable, and git platform agnostic. It is equivalent of github codespaces, with ad-hoc stateless/ephemeral dev environments generated and the presented in the browser. It uses Theia (open source VS Code) as it's IDE, and is integrated with a vender neutral VS Code extensions repository.

Gitpod's SaaS service is free for those who use it on open source projects, and its use should offer a one click browser based demo to use along side tutorial documentation.

**Additional Information**

I'm not seeing any immediate method of conversion, (single time, or automated sync) between devspaces.json and gitpod.yml. Config details should easily be cross referenceable to be mirrored between the two formats though. From what I understand, gitpod.yml leverages docker in the same or nearly identical way as devcontainer.json.

[Gitpod Docs - Environment Variables](https://www.gitpod.io/docs/environment-variables/)

I will also be submitting a request with gitpod to enable compatibility with using a dockerfile and devcontainer to auto generate a gitpod.yml ad-hoc, so as to improve the experience in general, going forward.

If possible, I would suggest the use of gitpod (and devspaces, as it serves different though slightly overlapping purposes) on all demo/tutorial repositories. 

Additionally, you can open web-ui instances that originate from the sandboxed gitpod dev instance, something relevant I think to many demos/tutorials. See the below example link which details the method with a Nuxt.js dev environment as an example use case.

[Gitpod Blog - Developing NUXT.js in Browser](https://www.gitpod.io/blog/developing-nuxtjs-in-browser/)

**Comment by NukeManDan** [comment]
@miseenplace any updates? 😁 
More and more people are interested in docker development with substrate!

**Comment by jimmychu0807** [comment]
@miseenplace you are right that we should probably better integrate with some online editor and saving people from compiling their own node template. We have [Substrate Playground](https://github.com/paritytech/substrate-playground) for this sake and will better integrate with it and have a link in our readme linking people to there.
