### ISSUE TITLE
panic while trying to run a private chain

### ISSUE THREAD

**Issue by telostia** [substrate-developer-hub/substrate-node-template#121]
**Description**
It panicked on a runtime when use --chain, --dev works though

**Steps to Reproduce**

1. git clone https://github.com/substrate-developer-hub/substrate-node-template.git
2. cd substrate-node-template
3. make init
4. make build
5. .# Start Alice's node
./target/release/node-template \
  --base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9945 \
  --rpc-port 9933 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator

**Expected vs. Actual Behavior**

Expected chain to start as usual but it actually panicked as below

**Environment**
Ubuntu 18.04 and 16.04 linux

_Describe the environment in which you encountered this bug. Use the list below as a starting point
and add additional information if you think it's relevant._

- Operating system:
- Template version/tag:
- Rust version (run `rustup show`):
- rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2020-10-05-x86_64-unknown-linux-gnu(default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2020-10-05-x86_64-unknown-linux-gnu (default)
rustc 1.48.0 (7eac88abb 2020-11-16)

**Logs, Errors or Screenshots**

.# Start Alice's node
e \
  --base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9945 \
  --rpc-port 9933 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validatorroot@vmi221805:~/substrate# ./target/release/node-template \
>   --base-path /tmp/alice \
>   --chain local \
>   --alice \
>   --port 30333 \
>   --ws-port 9945 \
>   --rpc-port 9933 \
>   --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
>   --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
>   --validator
Dec 26 21:14:22.511  INFO Substrate Node    
Dec 26 21:14:22.511  INFO ✌️  version 2.0.0-37f7720-x86_64-linux-gnu    
Dec 26 21:14:22.511  INFO ❤️  by Anonymous, 2017-2020    
Dec 26 21:14:22.511  INFO 📋 Chain specification: Local Testnet    
Dec 26 21:14:22.511  INFO 🏷  Node name: Alice    
Dec 26 21:14:22.511  INFO 👤 Role: AUTHORITY    
Dec 26 21:14:22.512  INFO 💾 Database: RocksDb at /tmp/alice/chains/local_testnet/db    
Dec 26 21:14:22.512  INFO ⛓  Native runtime: node-template-1 (node-template-1.tx1.au1)    
Dec 26 21:14:22.710  INFO 🔨 Initializing Genesis block/state (state: 0xe5ae…6329, header-hash: 0x7ede…07f0)    
Dec 26 21:14:22.716  INFO 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
Dec 26 21:14:22.782  INFO ⏱  Loaded block-time = 6000 milliseconds from genesis on first-launch    
Dec 26 21:14:22.782  WARN Using default protocol ID "sup" because none is configured in the chain specs    
Dec 26 21:14:22.785  INFO 🏷  Local node identity is: 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp (legacy representation: 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp)    
Dec 26 21:14:22.828  INFO 📦 Highest known block at #0    
Dec 26 21:14:22.829  INFO 〽️ Prometheus server started at 127.0.0.1:9615    
Dec 26 21:14:22.836  INFO Listening for new connections on 127.0.0.1:9945.    
====================

Version: 2.0.0-37f7720-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/core/src/panicking.rs:85
   6: core::option::expect_none_failed
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/core/src/option.rs:1234
   7: <libp2p_mdns::behaviour::Mdns as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   8: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   9: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler,TConnInfo>::poll_next_event
  10: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  11: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: std::thread::local::LocalKey<T>::with
  17: futures_executor::local_pool::block_on
  18: tokio::runtime::task::core::Core<T,S>::poll
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  20: tokio::runtime::task::harness::Harness<T,S>::poll
  21: tokio::runtime::blocking::pool::Inner::run
  22: tokio::runtime::context::enter
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: core::ops::function::FnOnce::call_once{{vtable.shim}}
  25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/ef663a8a48ea6b98b43cbfaefd99316b36b16825/library/std/src/sys/unix/thread.rs:87
  26: start_thread
  27: clone

Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ResponseTooLong', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.22.0/src/behaviour.rs:296

This is a bug. Please report it at:

**Additional Information**

tried on some vps with 16.04 and 18.04. A fresh vps seems to work but a current failed on me on 3 occassions.

**Comment by danforbes** [comment]
Did you launch another node first? You're passing this parameter, which tells the node to expect another node to be running locally that it can connect to `--bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp`

**Comment by telostia** [comment]
which node? im just following the tutorial to run a private chain

**Comment by telostia** [comment]
https://github.com/libp2p/rust-libp2p/pull/1877 seems to fix it but how do we use the latest libp2p or update ourselves @danforbes

**Comment by telostia** [comment]
I have found a way around this bug. People who ran into this issue can try it out to get a panic.
Have 64 ipv6 on ubuntu 16.04 or 18.04 , build and run it.

Solved:
I concluded that the mdns error problem was due to the amount of ipv6 on the system so to rectify it, you have to reduce the amount of ipv6 count. Personally i reduced from 64 ipv6 addresses to 30 and it works like a charm( even the new libp2p patch didn't fix this issue that i've tried). Have a nice day!
