### ISSUE TITLE
build failed on apple silicon 'M1'

### ISSUE THREAD

**Issue by Jean332** [substrate-developer-hub/substrate-node-template#122]
aarch64-apple-darwin is a tier2 target, rust can run natively on my Macbook, but when I build substrate-node-template,meet some trouble.
 
When I use nightly-2020-12-26 to build ,it report an error`type annotations needed`,so I follow #108 

but when I try:
` rustup install nightly-2020-10-06`
info: latest update on 2020-10-06, rust version 1.49.0-nightly (a1dfd2490 2020-10-05)
error: target 'aarch64-apple-darwin' not found in channel.  Perhaps check https://forge.rust-lang.org/release/platform-support.html for available targets

which version of nightly is available for 'M1' ? or any other way to run substrate on M1? A thousand thanks for your help!

**Comment by danforbes** [comment]
@xlc can you offer some insight here? 🙏🏻

**Comment by xlc** [comment]
You cannot build Substrate 2.0 with M1 as it requires an old Rust version that does not have M1 support. 

For Substrate master, have everything installed nativity including rustup and llvm, use cargo config to override rust-rocksdb with this version https://github.com/hdevalence/rust-rocksdb/commit/33cd4281570b229b628d6d827fa0053cff57000a and you should be good to go

**Comment by Jean332** [comment]
> You cannot build Substrate 2.0 with M1 as it requires an old Rust version that does not have M1 support.
> 
> For Substrate master, have everything installed nativity including rustup and llvm, use cargo config to override rust-rocksdb with this version [hdevalence/rust-rocksdb@33cd428](https://github.com/hdevalence/rust-rocksdb/commit/33cd4281570b229b628d6d827fa0053cff57000a) and you should be good to go

 I'm so excited!  after overriding rust-rocksdb, I can run substrate successfully😄Thank you vvvvvery much!!

**Comment by bobjiang** [comment]
@xlc @Jean332 Is it substrate2.0 or node template to work well with Apple M1? (or maybe it is the same thing substrate 2.0 with node template.) -- I am a newbie for substrate and trying to building my dev env on M1.

**Comment by xlc** [comment]
You will need to use the latest Substrate master, or https://github.com/paritytech/substrate/pull/7686
