### ISSUE TITLE
Do not use depricated substrate-wasm-builder-runner

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-node-template#127]
**Motivation**

This dependence is deprecated: https://github.com/substrate-developer-hub/substrate-node-template/blob/4d97032c11b8c65936e53a61607d4522d45a29ea/runtime/Cargo.toml#L14

**Suggested Solution**

Basti (`@bkchr`) suggests looking at substrate's master node implimentation to update to the new method: https://crates.parity.io/substrate_wasm_builder/index.html
See the docs here for details on how to migrate.

**Alternatives**

leave as is at our own risk ☠️ 

**Additional Information**

we should scan our dependencies for deprecations like this.... I am not sure how to automate it other than a `yank` from crates.io for dependencies, so you get  a warning when building. There may be cargo extensions to help...

**Comment by danforbes** [comment]
I wonder if we should include this in #126?

**Comment by NukeManDan** [comment]
Solved in #126
