### ISSUE TITLE
init script to include install of rust

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-node-template#129]
**Motivation**
We could have a one line install to get started from a completely clean machine with

`make init`

The UX here would be 😽 👌🏼 

**Suggested Solution**

We can add a check for rust being installed, and if not, run the install script *for the user's OS*
I have seen this done in other make files and can investigate. One possible exception being windows, where I would instead provide an error message kindly suggesting to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or a linux distro and closing out.

**Alternatives**

Direct to the docs as we do now: https://substrate.dev/docs/en/knowledgebase/getting-started/
This is less optimal, as its time consuming for no good reason IMHO for the user. They don't learn anything new about substrate or rust by doing this.

**Comment by NukeManDan** [comment]
basically this: https://getsubstrate.io/

**Comment by g2udevelopment** [comment]
@NukeManDan If you agree that this is a good direction I could grab the script modify it and put it in the make file.

**Comment by NukeManDan** [comment]
@g2udevelopment https://github.com/paritytech/scripts/issues/253 
I have opened up a new issue on a vision for a fully featured `create` or `init` style script that would include updating and making our `make init && make build` smarter. 

Would be honoured to have you make some suggestions there on it, and if you are interested, help craft such a thing 😁

**Comment by g2udevelopment** [comment]
@NukeManDan I think the first step should be to port over the script from `getsubstrate` into this repository. Because this repo will likely be the first point of entry for any aspiring substrate developer. After that we can see if there is some need for a more CLI like tool.
