### ISSUE TITLE
ws://127.0.0.1:9944: 1006:: Abnormal Closure

### ISSUE THREAD

**Issue by kirankumarhm** [substrate-developer-hub/substrate-node-template#137]
I encountered an error, when I tried to debug found its coming from react node module as shown in the below screen.
*node_modules/react-error/overlay/index.js*

My Configuration is :
Node template is running on AWS ubuntu machine and nginx has been configured for the secured web socket as per the [link](https://wiki.polkadot.network/docs/en/maintain-wss)

And substrate-front-end-template am running from Windows.
![2021-02-02 17_52_59-](https://user-images.githubusercontent.com/6735087/106600432-6fbfeb80-6580-11eb-9ea9-6fe2465d4895.png)

Please help me to resolve this issue.

**Comment by jimmychu0807** [comment]
@kirankumarhm If you are deploying in AWS, is the frontend running on the same server as well? As it is connecting to `127.0.0.1`. Also could you use [polkadot js app](https://polkadot.js.org/apps) to connect to your substrate node?

**Comment by NukeManDan** [comment]
Checking in here @kirankumarhm  - Did you resolve your problem? If so can you report what worked? If you need more support, please do repoen this issue! 😁
