### ISSUE TITLE
fail to run librocksdb-sys on apple silicon

### ISSUE THREAD

**Issue by jyooi** [substrate-developer-hub/substrate-node-template#139]
<img width="785" alt="Screenshot 2021-02-09 at 2 21 53 PM" src="https://user-images.githubusercontent.com/42993221/107324035-448a4e80-6ae2-11eb-98bf-de4a94f961af.png">

**Comment by Yuripetusko** [comment]
@jyooi why did you close this and how can I solve it. I'm on M1 also and getting the same error

**Comment by jyooi** [comment]
@Yuripetusko  currently, librocksbd  not support m1 but I found a workaround way to resolve the issue by following this guide  by guide  https://zhuanlan.zhihu.com/p/337224781 and the original issue https://github.com/rust-rocksdb/rust-rocksdb/issues/482, I hope it help

**Comment by jyooi** [comment]
after I made the changes, still I got another error 
<img width="1440" alt="Screenshot 2021-02-14 at 8 59 14 AM" src="https://user-images.githubusercontent.com/42993221/107865704-5da94b80-6ea4-11eb-9ead-4e224ff1dec0.png">

**Comment by jyooi** [comment]
resolve it by change the (*cx.uc.mcontext).__ss.__rip -> __pc

**Comment by Yuripetusko** [comment]
Thank you @jyooi that actually worked.

![image](https://user-images.githubusercontent.com/666169/107891412-65a1d380-6f16-11eb-85e3-ffc5f7d4c983.png)

**Comment by meck93** [comment]
> resolve it by change the (*cx.uc.mcontext).__ss.__rip -> __pc

@jyooi how did you resolve the `wasmtime-runtime` compile issue? did you fork it and fix yourself locally?

**Comment by jyooi** [comment]
@meck93, nope I didn't fork it, just fixed it locally.
