### ISSUE TITLE
tutorials upgrade-a-chain

### ISSUE THREAD

**Issue by xgrowingpains** [substrate-developer-hub/substrate-node-template#142]
**Description**

I found a problem when I was studying the tutorial. In the Use the sudo palet section of upgrade-a-chain, I modified the effect of real-time refresh of the version runtime. If the version number is lower than 100, the expected effect cannot be achieved.

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

1. Go to 'tutorials'--‘upgrade-a-chain’
2. Click on 'Use the sudo palet'
3. Scroll down to 'spec_version: 2,  // Update this value.'
4. When the version is set to 2, the version cannot be updated after compilation. Only when the version is set to a value greater than 100, such as 102, will the version be updated. Similarly, when the later version is set to 3, we will encounter this problem, and we need to set the version to 103

![image](https://user-images.githubusercontent.com/30177688/108796564-fc7c2900-75c3-11eb-8dd1-856fe1a866ce.png)

![image](https://user-images.githubusercontent.com/30177688/108796623-19186100-75c4-11eb-9d05-4541c6c9dc21.png)

**Comment by NukeManDan** [comment]
Thanks for the report!!!

I see that v3 of the node template [uses version 100](https://github.com/substrate-developer-hub/substrate-node-template/blob/v3.0.0/runtime/src/lib.rs#L99), and as you would expect, you must increment this value, any lower value will be rejected. 

For v2 this started at spec_version = 1. The tutorial is about to be [updated to v3](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/884) that will include instructions. For now try 101 for the version of your upgraded runtime.
