### ISSUE TITLE
Substrate-Node-template Compiling Failure - with Apple M1 Chip, Big Sur 11.2.1 OS

### ISSUE THREAD

**Issue by IPConvergence** [substrate-developer-hub/substrate-node-template#144]
**Description**

_Tell us what happened. 

I follow all the steps mentioned on the procedure mentioned at https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup

When executing "$make build" on the node template, everything is running fine, excepted for compiling "librocksdb-sys v6.11.4". It fails at that step

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

**Expected vs. Actual Behavior**

The Node Template should finish compiling without any error.

**Environment**

_Describe the environment in which you encountered this bug. Use the list below as a starting point
and add additional information if you think it's relevant._

- Operating system: Big Sur 11.2.1 with Apple M1 Chip
- Template version/tag: 2.0.1
- Rust version (run `rustup show`):

Default host: aarch64-apple-darwin
rustup home:  /Users/lemaimn/.rustup

installed toolchains
--------------------
stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------
aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------
stable-aarch64-apple-darwin (default)
rustc 1.50.0 (cb75ad5db 2021-02-10)

**Logs, Errors or Screenshots**

   ....    
   Compiling jsonrpc-ipc-server v15.1.0
   error: failed to run custom build command for `librocksdb-sys v6.11.4`

Caused by:
  process didn't exit successfully: `/Users/lemaimn/Documents/blockchain/devCode/Substrate/myFirstSubstrate3/substrate-node-template/target/release/build/librocksdb-sys-e9a581271a3b2145/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'libclang error; possible causes include:
  - Invalid flag syntax
  - Unrecognized flags
  - Invalid flag arguments
  - File I/O errors
  - Host vs. target architecture mismatch
  If you encounter an error missing from this list, please file an issue or a PR!', /Users/lemaimn/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.54.0/src/ir/context.rs:573:15
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [build] Error 101

**Additional Information**

_Please add any other details that you think may help us solve your problem._

**Comment by NukeManDan** [comment]
M1 is _not_ well supported, and this is an upstream issue unfortunately. 😭 Best for now is to wait for better rust & M1 support or use a different machine. Further I see you must be using substrate v2 - please use v3 [updates to the docs](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/labels/v3-tutorial-update) are inbound or in place. 

This article may help if you want to try anyway: https://vikiival.medium.com/run-substrate-on-apple-m1-a2699743fae8.

Also a community member reports needing to: 
> You need clone the rust-rocksdb repo and checkout the commit listed here: https://github.com/substrate-developer-hub/substrate-node-template/issues/122 then you can create a config.toml file in your .cargo folder in your home directory and add a path to that cloned repo

**Comment by VadneyK** [comment]
Having similar but slightly different issue with same computer and env setup:

Any ETA for when substrate will be compatible with M1?

<img width="1222" alt="Screen Shot 2021-05-16 at 10 14 06 PM" src="https://user-images.githubusercontent.com/57117207/118435553-09c12500-b694-11eb-8539-13a9905113ea.png">

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-node-template/issues/179#issuecomment-839233695
This is a hack you can try ☝🏼 

There are still upstream problems, no ETA on those AFAIK.

**Comment by bidibidibum** [comment]
Hi everyone I am completely new to Rust and Substrate and attempted following the instructions as per: https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup

I use a MacBook Air 2020 (Apple Silicon M1 Chip) and when I enter into my terminal:

# Run a temporary node in development mode
./target/release/node-template --dev --tmp

I get the following error:
bidibidibum@bidibidibums-MacBook-Air ~ % # Run a temporary node in development mode
./target/release/node-template --dev --tmp
zsh: command not found: #
zsh: no such file or directory: ./target/release/node-template
bidibidibum@bidibidibums-MacBook-Air ~ % 

Is the latest recommendation to still follow #179 (comment) as @NukeManDan mentions above? It's quite confusing for a beginner like me and I want to make my project work so keen to hear if there have been updates since May/June. thanks very much!
