### ISSUE TITLE
Bad input data provided to xxx when send transaction.

### ISSUE THREAD

**Issue by tyan-boot** [substrate-developer-hub/substrate-node-template#145]
**Description**

When interact with the node using polkadot.js.org, all transaction failed with:
```
1002: Verification Error: Runtime error: Execution failed: Wasmi(Trap(Trap { kind: Unreachable })): RuntimeApi, Execution failed: Wasmi, Trap, Trap { kind: Unreachable }
```

and the node log
```
2021-02-25 15:08:28  panicked at 'Bad input data provided to query_info: ', /substrate-node-template/runtime/src/lib.rs:322:1    
```

**Steps to Reproduce**

1. `cargo build --release` with latest commit `d567c877076fbe55fca43b5129b3b26d18c14f2a`
2. `target/release/node-template --dev`
3. open `polkadot.js.org` and send any transaction.

**Expected vs. Actual Behavior**

failed with:
```
balances.transferKeepAlive
1002: Verification Error: Runtime error: Execution failed: Wasmi(Trap(Trap { kind: Unreachable })): RuntimeApi, Execution failed: Wasmi, Trap, Trap { kind: Unreachable }
```

**Environment**

- Operating system: Arch Linux
- Template version/tag: d567c877076fbe55fca43b5129b3b26d18c14f2a
- Rust version (run `rustup show`): rustc 1.49.0-nightly (beb5ae474 2020-10-04)

**Logs, Errors or Screenshots**

```
2021-02-25 15:25:28  panicked at 'Bad input data provided to query_info: ', substrate-node-template/runtime/src/lib.rs:322:1    
2021-02-25 15:25:33  panicked at 'Bad input data provided to validate_transaction: ', substrate-node-template/runtime/src/lib.rs:322:1    
2021-02-25 15:25:33  Failed to submit extrinsic: Extrinsic verification error: Runtime error: Execution failed: Wasmi(Trap(Trap { kind: Unreachable }))    
```

**Comment by jimmychu0807** [comment]
Please update your rust toolchain to use the `stable`. Also ensure you have target environment `wasm32-unknown-unknown` installed.

Run

```bash
rustup default stable
rustup update
# run this if you unsure if `wasm32-unknown-unknown` is installed.
rustup target add wasm32-unknown-unknown 
```

**Comment by NukeManDan** [comment]
@tyan-boot - are you still having issues after the suggested fix? If so, please reopen this issue so we can help!
