### ISSUE TITLE
Feat Req: Have master/main branch be usable for all devhub tutorials/docs

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-node-template#148]
## Motivation

![image](https://user-images.githubusercontent.com/35669742/109851970-81dd8a00-7c11-11eb-922a-635fc2df4358.png)
Using the "use this template" button on the node template directs [here](https://github.com/substrate-developer-hub/substrate-node-template/generate) - and it can only take from the master (the default) branch (or all branches get copied).

## Would it be possible to 

Keep master/main branch pinned to a specific release (v3.0.0), and have updates on another branch to let people pull a template from the default branch for almost all use cases. 

**Alternatives**

Update the docs here to "use this template" with all branches, and select the versioned branch manually, then delete all other branches (this is a bit of a PITA IMHO)

**Comment by jimmychu0807** [comment]
I think this is a good idea. Let's keep `main`/`master` to v3.0.0 tag, and do the latest development in branch `development`.

**Comment by NukeManDan** [comment]
Related: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/727
It seems that there is still no agreement on this 🤔

**Comment by jimmychu0807** [comment]
@NukeManDan @sacha-l 
I made a `development` branch in this repo. Let's remember to keep `master` as the latest stable, and all fixes go to `development`. I think I need some additional settings with `maintainer` right to config. Will see if I can get the right.

**Comment by NukeManDan** [comment]
With #186 onward, I think we won't try to maintain this. It's ok, the same behavior can be achieved with:

```
git clone -b <tag> --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
```

as the template button provides.
