### ISSUE TITLE
Error : make: *** [Makefile:3: init] Error 2 substrate node template #150

### ISSUE THREAD

**Issue by mtgnoah** [substrate-developer-hub/substrate-node-template#151]
**Description**

I have tried switching from nightly to stable and also tried using different versions of rust but this issue is constant when I run make init for the substrate node template.
`make init ./scripts/init.sh process_begin: CreateProcess(NULL, env bash C:\Users\noahp\substrate-node-template\scripts\init.sh, ...) failed. make (e=2): The system cannot find the file specified. make: *** [Makefile:3: init] Error 2`

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

I just followed these steps: 
[https://substrate.dev/docs/en/knowledgebase/getting-started/windows-users](url)
git clone -b v2.0.1 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
cd substrate-node-template
make init

_What did you expect to happen after you followed the steps you described in the last section? What
actually happened?

It won't find the file but the file is there and I have tried downloading the substrate node template in multiple different ways. 

**Environment**

- Operating system: Windows 10 
- Template version/tag: V2.0.1
- Rust version : 
installed toolchains

stable-x86_64-pc-windows-msvc (default)
nightly-2020-10-05-x86_64-pc-windows-msvc
nightly-2020-10-06-x86_64-pc-windows-msvc

installed targets for active toolchain

wasm32-unknown-unknown
x86_64-pc-windows-msvc

active toolchain

stable-x86_64-pc-windows-msvc (default)
rustc 1.50.0 (cb75ad5db 2021-02-10)

**Logs, Errors or Screenshots**

![image](https://user-images.githubusercontent.com/5161963/110215558-0c232980-7e70-11eb-8d08-da608c1d7d60.png)

**Comment by jimmychu0807** [comment]
@mtgnoah I believe our script is not windows compatible. In our latest version or [v3.0.0](https://github.com/substrate-developer-hub/substrate-node-template/tree/v3.0.0), we no longer have `scripts/init.sh`.

Assuming you are running Substrate v3.0.0, once you have setup your Windows machine [according to instructions here](https://substrate.dev/docs/en/knowledgebase/getting-started/windows-users), you just need to ensure you are using toolchain `stable` (which you are) and have `wasm-unknown-unknown` target installed (run `rustup target add wasm-unknown-unknown` if unsure).

Then you should be able to compile the node template project by running `cargo build` in the project root directory.

**Comment by NukeManDan** [comment]
@mtgnoah please use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) if you are on windows, as windows native is known to give issues and is not well supported by us. If you still have issues using WSL, please open a new issue here 🙏🏼
