### ISSUE TITLE
use new 3.0.0 compiler flags for pallets/template

### ISSUE THREAD

**Issue by brenzi** [substrate-developer-hub/substrate-node-template#152]
What is the reason why the `pallets/template` still use the macros? 

https://github.com/substrate-developer-hub/substrate-node-template/blob/8370ddd69caf4fe8c6251b99b2f6f3ea0008de8e/pallets/template/src/lib.rs#L24

in the substrate repo this looks different:
https://github.com/paritytech/substrate/blob/49a4103f4bfef55be20a5c6d26e18ff3003c3353/bin/node-template/pallets/template/src/lib.rs#L33

I suggest to keep this node template in line with the substrate repo

**Comment by brenzi** [comment]
I realize that all the  recipies doc isn't yet updated to substrate 3.0.0, so I can understand that the template stays with this....

But: what's the strategy?

**Comment by NukeManDan** [comment]
FRAME v2 and v1 are both supported in substrate v3 - I am with you on moving to the new version, but this should happen only _after_ all of devhub is updated to v3

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues?q=is%3Aissue+is%3Aopen+label%3Av3-tutorial-update

**Comment by GopherJ** [comment]
I'm really confused on the syntax while learning substrate...Is it possible to upgrade all code to v3.0? that helps new learner like me

**Comment by NukeManDan** [comment]
@GopherJ FRAME v2 macros in substrate v3 are not _that_ different in concept, but IMHO easier to read. If you understand FRAME v1, the transition is not too bad. Checkout these resources:

- https://github.com/paritytech/substrate/releases/tag/v3.0.0
- https://github.com/paritytech/substrate/blob/master/docs/Upgrading-2.0-to-3.0.md
- https://crates.parity.io/frame_support/attr.pallet.html

And be sure to join us on matrix to get further questions answered: https://matrix.to/#/#substrate-technical:matrix.org

**Comment by jimmychu0807** [comment]
I think this issue eventually boil down to three points.

1. @brenzi: Node template is using the old macro style `decl_*`, it is solved with the tagged version of `v3.0.0+1`. The recipe has also just recently updated to using Substrate v3, thanks to @JoshOrndorff  contribution. So this is addressed.

2. @GopherJ yea, currently Substrate supports both `decl_*` procedural macros and `#[pallet:*]` attribute macros (aka FRAME v2) syntax. If you want to learn about the attribute macro syntax, THE best resource is referring to this [API rustdoc page](https://substrate.dev/rustdocs/v3.0.0/frame_support/attr.pallet.html). But there is no harm to know about the `decl_*` syntax as well. So the doc part is also addressed.

3. We have colleague working on FRAME v2 documentation in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io and should be launching that soon, but I believe it will be partly derived from the above API rustodoc page. So you could still refer to that page for now.
