### ISSUE TITLE
dependecy sp-arithmetic 2.0.0 failing to build nicks pallet

### ISSUE THREAD

**Issue by julianclatro** [substrate-developer-hub/substrate-node-template#153]
**Description**

Missing type for sp-arithmetic. error: Consider giving `accuracy` a type

**Steps to Reproduce**

1. checkout to branch tutorials/solutions/add-a-pallet
2. run cargo build --release

**Expected vs. Actual Behavior**

Fails to build

**Environment**

- Operating system: Mac OS Catalina
- Rust nightly 1.52.0

**Logs, Errors or Screenshots**
![image](https://user-images.githubusercontent.com/6716921/110351698-d9b23180-8013-11eb-942e-0b1e02abf5be.png)

**Comment by hzy1919** [comment]
Maybe you can try to update the version to "3.0.0"

**Comment by julianclatro** [comment]
As far as i know nicks pallets only works on versions 2.0.0 and 2.0.1, the only tutorial that works on substrate 3 is "create a pallet".

Did you successfully run this tutorial?

**Comment by NukeManDan** [comment]
Nicks is available in v3 (presently in master as well as tagged v3.0.0)
 https://github.com/paritytech/substrate/blob/master/frame/nicks/Cargo.toml
 
Please try to do this with v3 for everything, and expect devhub to be updated soon: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/882 is in the works to help with this.

[Tracking issues](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues?q=is%3Aissue+is%3Aopen+label%3Av3-tutorial-update)

**Comment by NukeManDan** [comment]
If you can't get v3 to work on your, please wait for the incoming v3 tuto update, or @ me in the substrate technical for further support: https://matrix.to/#/#substrate-technical:matrix.org I am `@dan.shields:matrix.parity.io`
