### ISSUE TITLE
Error when opening substrate node on localhost 

### ISSUE THREAD

**Issue by ValoisProtocol** [substrate-developer-hub/substrate-node-template#155]
when running my substrate node, it opens fine on polkado.js/app
however on localhost via yarn start i recieve this error

```
Error Connecting to Substrate
Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
```

**Comment by NukeManDan** [comment]
what version of the frontend template are you using? Ideally you should be using v3 throughout:
https://github.com/substrate-developer-hub/substrate-front-end-template/tree/v3.0.0
https://github.com/substrate-developer-hub/substrate-node-template/tree/v3.0.0

**Comment by ValoisProtocol** [comment]
all  fixed buddy
