### ISSUE TITLE
Build error substrate-node-template v3.0.0

### ISSUE THREAD

**Issue by J-Cook-jr** [substrate-developer-hub/substrate-node-template#156]
Hi, I'm having issues after running the run/build command in this repo. I cloned the git repo tag v3.0.0 for substrate-node template but it isn't building for me. I'll take you through step by step for what I did .

1. I ran rust update
2. I ran rust update nightly, that was successful

<img width="1280" alt="Screen Shot 2021-03-16 at 1 31 26 PM" src="https://user-images.githubusercontent.com/62865359/111353890-1dccb400-865c-11eb-8e29-17fc0be3d3ab.png">

3. Next, I  ran the "rust-up target wasm" command
4. I cloned the repo and was also successful

<img width="831" alt="Screen Shot 2021-03-16 at 1 34 19 PM" src="https://user-images.githubusercontent.com/62865359/111354454-b6633400-865c-11eb-8b0d-91114d806f06.png">

Even though the above steps were successful, I still ran into build errors. Please help me out, thanks!

<img width="640" alt="Screen Shot 2021-03-16 at 1 37 38 PM" src="https://user-images.githubusercontent.com/62865359/111354989-4903d300-865d-11eb-8397-4fd79773727e.png">
<img width="1280" alt="Screen Shot 2021-03-16 at 1 37 45 PM" src="https://user-images.githubusercontent.com/62865359/111355021-515c0e00-865d-11eb-9278-5d2e1cd63a2e.png">

**Comment by shawntabrizi** [comment]
@J-Cook-jr try `rustup default nightly` then `cargo build --release`?

Indeed it seems you have followed all the steps correctly

**Comment by NukeManDan** [comment]
You may also need to install the wasm toolchain:
`rustup target add wasm32-unknown-unknown`

**Comment by NukeManDan** [comment]
I am also seen an `output file collision` in the errors you show, try to completely clear cargo arfitacts:
`cargo clean`
and try again 🙏🏼 
you can also do:
`rm -rf target` 
that will clear _all_ build data.

**Comment by J-Cook-jr** [comment]
Ok @NukeManDan , do I run those commands in the node-template directory or my "projects" directory?

**Comment by J-Cook-jr** [comment]
@shawntabrizi , thanks I will try this as well.

**Comment by shawntabrizi** [comment]
> Ok @NukeManDan , do I run those commands in the node-template directory or my "projects" directory?

All commands should be run inside the node-template directory

**Comment by J-Cook-jr** [comment]
Got it! Thanks @shawntabrizi

**Comment by J-Cook-jr** [comment]
@shawntabrizi , when you say all commands should be run inside the node template directory, you are referring to the build and run commands right? Because the installation guide on substrate.dev doesn't specify those instructions. Correct me if I'm wrong, but the command you advised me  to run (rustup default nightly) in my node-template directory , is actually supposed to be ran during the "Rust Developer Environment" step according to the instructions on substrate.dev . But those instructions are prior to cloning the node-template git repo right?

**Comment by NukeManDan** [comment]
All commands are expected to originate from the node template's root directory unless explicitly stated otherwise.
When installing you don't have the node cloned yet, you can run the commands from any directory

**Comment by J-Cook-jr** [comment]
Thanks @shawntabrizi and @NukeManDan  the above commands solved my issue.
