### ISSUE TITLE
nightly build version

### ISSUE THREAD

**Issue by J-Cook-jr** [substrate-developer-hub/substrate-node-template#157]
**Question**

In what case would I have to specify the nightly build "date" ?  I haven't had to do it so far, but incase I run into an issue, I would like to know. Also where would I need to look to find the nightly build "date" for specific projects? Thanks!

**Comment by NukeManDan** [comment]
@J-Cook-jr for me I run with the latest nightly, updating a few times a week. This is fine for me as I don't have any production code running, so breaking isn't an issue. 

If you intend on having a stable build that you want to rely on and share, sticking to a specific toolchain is best practice for sure. My advice:
1. update and use the latest versions in testing
2. if things build fine, take note of the exact toolchain `rust show` you use
3. when sharing a release, specify the exact toolchain and flags to use for others to build from. 

LMK if that solves your question here 😁 - this is just fine to ask in https://matrix.to/#/#substrate-technical:matrix.org ! And if you want to create an issue as a question, https://github.com/paritytech/subport/issues is best next time 😁

**Comment by J-Cook-jr** [comment]
Thanks @NukeManDan , will do. You answered my question!
