### ISSUE TITLE
Compiling problems on MacOs Big Sur with Apple M1 Chip

### ISSUE THREAD

**Issue by tinydjp** [substrate-developer-hub/substrate-node-template#158]
**Compiling problems on MacOs Big Sur with Apple M1 Chip**

_Is there any official guide that I can follow to build the node template on Mac `Big Sur` with M1 chip, I've searched around but all failed._

**Comment by NukeManDan** [comment]
Its not well supported for now, upstream issues 
Here is a community guide if you want to try before these are resolved:
https://vikiival.medium.com/run-substrate-on-apple-m1-a2699743fae8
