### ISSUE TITLE
Starting a frontend template also in the docker script

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-node-template#163]
We have `docker-compose.yml` and `scripts/docker_run.sh` for starting a docker container. Let's also allow starting a frontend template and connect to the node template (perhaps another service). Also allow a cli argument to control whether we want to start just the node template, or both node and frontend template. 

Raised at: https://github.com/paritytech/substrate/pull/8473#discussion_r602849440

**Comment by NukeManDan** [comment]
This seems related to what is done already in the https://github.com/paritytech/substrate-playground right? 
If so, we can maybe get some advice on how to correctly implement and document this. I think it would be a good feature 😁

**Comment by jimmychu0807** [comment]
I think a major component in playground is the online editor component (an online vs-code editor?). But in this node template docker script I am thinking just pulling the node-template and front-end template src as two docker services and start them. Somethings plain and simple.

**Comment by NukeManDan** [comment]
Ideally having an image that is per-comipled from this available is what I would want to see 🙏🏼 
Automatically or manually generated corresponding to each release/tag
