### ISSUE TITLE
How can I get the websocket endpoint to run on my lan ip address instead of localhost?

### ISSUE THREAD

**Issue by ILoomans** [substrate-developer-hub/substrate-node-template#165]
**Question**

Hello,

I have gone through some of the tutorials and added some pallets, I am trying to connect to my one node using a react-native app. I can't seem to establish a connection however. After doing some more research I found that the error could be that the websocket is being hosted from my computers localhost ip, instead of my lan ip. This would explain why on canvas ui I am able to connect to my node using my localhost ip, but not my lan ip. Is there any way i can deploy the node where it hosts by default on my devices lan ip? Thanks in advance for any help!

**Comment by NukeManDan** [comment]
Likely yes. You need to use the ws-external and rpc-external flags. 

Use the `--help` flag with your Node to see all options.
