### ISSUE TITLE
Benchmarking is broken

### ISSUE THREAD

**Issue by fzzr-** [substrate-developer-hub/substrate-node-template#166]
Actual for version (tag) `v3.0.0+1`.

It's impossible to build node with benchmarking feature because of:
- [`use frame_system_benchmarking::Pallet`](https://github.com/substrate-developer-hub/substrate-node-template/blob/v3.0.0%2B1/runtime/src/lib.rs#L463)
- [there's `Module` only, not `Pallet`](https://github.com/paritytech/substrate/blob/v3.0.0/frame/system/benchmarking/src/lib.rs#L37)

So, just replace that line with `use frame_system_benchmarking::Module as SystemBench;` please :)

**Comment by NukeManDan** [comment]
@jimmychu0807 would you mind fixing and testing this one? Happy to take it on if you don't want it.

**Comment by fzzr-** [comment]
Okay. That was a little more "complex" than I said earlier. I've done.

**Comment by jimmychu0807** [comment]
@NukeManDan will look into this.
