### ISSUE TITLE
"Blocking waiting for file lock on package cache" message when intializing node

### ISSUE THREAD

**Issue by KotaHemanthIITD** [substrate-developer-hub/substrate-node-template#17]
> **cargo run -- --base-path /tmp/alice --chain=local --alice --node-key 0000000000000000000000000000000000000000000000000000000000000001 --telemetry-url ws://telemetry.polkadot.io:1024 --validator**

While running above command. I'm getting **"Blocking waiting for file lock on package cache"**. I have tried "crate clean" but no help. Can someone point on cause for this issue and solution?

**Comment by kaichaosun** [comment]
Try this [solution](https://stackoverflow.com/questions/47565203/cargo-build-hangs-with-blocking-waiting-for-file-lock-on-the-registry-index-a?rq=1)

**Comment by KotaHemanthIITD** [comment]
https://users.rust-lang.org/t/cargo-package-cache-is-locked/34594. This solution fixed my issue. It's an rust issue.
