### ISSUE TITLE
Substrate-node-template does not compile

### ISSUE THREAD

**Issue by sayyedkamran** [substrate-developer-hub/substrate-node-template#174]
I am trying to compile substrate-node-template.  It does not compile with the following errors:

error: failed to run custom build command for `node-template-runtime v3.0.0 (C:\Users\Syed Kamran\Documents\GitHub\substrate-node-template\runtime)`

Caused By:

process didn't exit successfully: `C:\Users\Syed Kamran\Documents\GitHub\substrate-node-template\target\debug\build\node-template-runtime-88088dec9b03b446\buil

  ←[0m←[0m←[1m←[31merror←[0m←[1m:←[0m could not compile `pallet-transaction-pay

error: build failed

**Comment by NukeManDan** [comment]
As highly emphasized in the [windows install instuctions](https://substrate.dev/docs/en/knowledgebase/getting-started/windows-users) - you should be using WSL. Are you building natively? If so, do try WSL first.

It also seems your error is truncated. If you get this with WSL, please provide the full text. Happy to reopen if you get further errors 😁
