### ISSUE TITLE
Setting up a secure remote connection

### ISSUE THREAD

**Issue by ILoomans** [substrate-developer-hub/substrate-node-template#178]
**Question**

Hello, 

I have a question related to setting up a secure remote websocket connection. I have followed the relevant tutorials, specifically this kusama one which explains how to set it up with nginx and ssl certificates. 

https://wiki.polkadot.network/docs/en/maintain-wss

this is another article that explains the same thing
https://medium.com/huobi-global/kusama-parachain-auction-all-leading-projects-analysis-powered-by-promoteam-935063e48236

Problem is, that once  you set up this node, in order to connect to it via polkadot.js ui, you first have to navigate to the websocket endpoint with https, go into advanced settings and click on 'proceed to ... (unsafe)'. I found this to be an issue in web frameworks like react, api using express, however in react-native it worked fine. 
The error is this:
 API-WS: disconnected from wss://....com: 1006:: connection failed

Researching this a bit more led me to this

https://stackoverflow.com/questions/63824901/connect-via-wss-to-polkadot-full-noder-running-on-local-network-failed?answertab=active#tab-top

 In which indeed you can stop this problem by adding "NODE_TLS_REJECT_UNAUTHORIZED=0" to your start script, but this would only be okay for development environment. 

Has anyone solved this issue?

Thanks in advance

**Comment by NukeManDan** [comment]
https://wiki.polkadot.network/docs/en/maintain-wss#set-up-a-certificate

did you setup a proper cert? self-signed isn't going to work

**Comment by ILoomans** [comment]
@NukeManDan  Thanks so much, works perfectly now, super helpful!
