### ISSUE TITLE
Keep persistent state with contract pallet

### ISSUE THREAD

**Issue by ILoomans** [substrate-developer-hub/substrate-node-template#181]
**Question**

I followed the tutorial to add the contract pallet, compiled fine and got the node running perfectly. I was able to deploy an ink contract, query, transact on it etc. The issue is that i am losing the ability to interact with the smart contract around 2 hours after it is deployed. I understand that this is a persistence issue. 

However i did start the node with the following command:

./target/release/node-template --dev

Which i understand should keep the state.

**Steps to Reproduce**

git clone https://github.com/ILoomans/substrate-node-with-contract-pallet
cd substrate-node-with-contract-pallet
cargo build --release
./target/release/node-template --dev

Deploy smart contract with polkadot.js or canvas-ui
Interact with it for 2 hours and then sometime after any interaction will fail

Hope someone can help!

**Comment by NukeManDan** [comment]
you want to use a `--base-path` that you can inspect and reuse, it is shown in logs, default is in ~/.local somewhere, setting it to a more obvious location is good practice 😁 

You can avoid pruning state with `--pruning archive`, I don't _think_ this is necessary to have contract state persist. can you upload a gist with your full debug logs where this fails?

**Comment by ILoomans** [comment]
Thanks for the quick reply, ill use --base path aswell, here is my gist of the functions i am using 
deployContract works well and is consistent, no issue with that

Its on the fetchOwnerBalance that it only works for the first two hours of the contract deployment, after that it fails, i wrote down the error and its location in the gist. 
https://gist.github.com/ILoomans/e8cb55c72f8b1b274da7fc375cb5a6ba

**Comment by NukeManDan** [comment]
Ah I meant a gist of your node's debug logs ;)

**Comment by NukeManDan** [comment]
Ah but I see on further inspection that might not be the issue, [this call](https://gist.github.com/ILoomans/e8cb55c72f8b1b274da7fc375cb5a6ba#file-deploygetbalance-js-L69) fails?
    owner = owner.output.toHuman()

**Comment by ILoomans** [comment]
Unfortunately I still have this issue when adding --pruning archive here

**Comment by ILoomans** [comment]
Ill close this issue!

**Comment by NukeManDan** [comment]
Thank you so much for leaving a trail for others to follow to your solution with similar issues @ILoomans!! 🙇🏼
