### ISSUE TITLE
segfault on 'typenum' while compiling on docker

### ISSUE THREAD

**Issue by VadneyK** [substrate-developer-hub/substrate-node-template#187]
**Description**

cloned repo and made no changes. On an M1 mac so trying to run on docker.

**Steps to Reproduce**

opened root file in vscode, opened in default rust docker container as suggested by rust (since the local docker-composer.yml seems to fail), 

run: cargo run --release

see error:
<img width="927" alt="Screen Shot 2021-05-19 at 3 06 16 PM" src="https://user-images.githubusercontent.com/57117207/118890565-c47b3e00-b8b3-11eb-9a22-9d142aef28dc.png">

**Expected vs. Actual Behavior**

expect : compile
actual : not compile

**Environment**

- Operating system:

macOS BigSur 11.2.3 M1 chip, 8GB mem

- Rust version (run `rustup show`):
Default host: x86_64-unknown-linux-gnu
rustup home:  /usr/local/rustup

1.51.0-x86_64-unknown-linux-gnu (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)

**Logs, Errors or Screenshots**

screenshot above. Also restarting container produces same error:

<img width="734" alt="Screen Shot 2021-05-19 at 3 11 57 PM" src="https://user-images.githubusercontent.com/57117207/118891401-8f232000-b8b4-11eb-90f7-c1c4b65f2000.png">

**Comment by NukeManDan** [comment]
> 8GB mem

You are likely out of memory. Any `SIG*` errors I have run into stem from this. 

You need no less than 12 GB from what I have seen for most substrate based builds. Can you try allotting more RAM? be sure to monitor usage while building. `htop` is a good cli tool for this.

**Comment by VadneyK** [comment]
thanks! could you point me to a tutorial on how to add RAM to a docker container? 
<img width="1149" alt="Screen Shot 2021-05-28 at 2 11 00 PM" src="https://user-images.githubusercontent.com/57117207/120042244-88845f00-bfbe-11eb-9b6e-66bfb3e734f3.png">

<img width="1132" alt="Screen Shot 2021-05-28 at 2 11 14 PM" src="https://user-images.githubusercontent.com/57117207/120042265-92a65d80-bfbe-11eb-864e-a37aa62fe333.png">

I'm not quite familiar with docker or htop so I don't know how to allot more RAM

**Comment by NukeManDan** [comment]
thats htop - I would run this in a stand alone terminal and close all other processes.

Are you machine limited to 8 GB RAM? it appears so, unless you are running vscode in a container?
You need to _buy and install_ more RAM if you see htop moving into swap while building and close all other processes too.

**Comment by VadneyK** [comment]
Oh I see. I only have 8 GB ram and am able to compile and run the program without the docker container. The image above is running the vscode in the docker container. I wanted to know how to dedicate more ram to the docker container in vscode so I can run it in there so I can run the code in a virtual ubuntu sandbox in case there are any more M1 errors down the line

**Comment by NukeManDan** [comment]
Closing this, as I think this is stale... Are you still getting errors? Possibly related to #212 ?
