### ISSUE TITLE
“An extrinsic failed” when following Add a Pallet to Your Runtime tutorial

### ISSUE THREAD

**Issue by led73** [substrate-developer-hub/substrate-node-template#190]
**Question**

I added nicks pallet as in [Add a Pallet to Your Runtime](https://substrate.dev/docs/en/tutorials/add-a-pallet/interact-with-a-pallet) tutorial 

My changes are here https://github.com/led73/substrate-node-template/commit/8f3025a73b35804edf7c8dd7cd5630b387f2d344

But when I try to interact with the pallet and `setName`, it fails with event 

```
system:ExtrinsicFailed:: (phase={"ApplyExtrinsic":1})-0
DispatchError: {"Module":{"index":9,"error":0}}, DispatchInfo: {"weight":50000000,"class":"Normal","paysFee":"Yes"}
An extrinsic failed. \[error, info\]
```

Where should I look for what went wrong?

<img width="1312" alt="Screen Shot 2021-05-30 at 6 44 55 AM" src="https://user-images.githubusercontent.com/85057812/120152141-cd460b00-c1f5-11eb-80fd-fb92111587df.png">

**Comment by al3mart** [comment]
Closing this as it is solved at https://stackoverflow.com/a/67769831/4763774
