### ISSUE TITLE
Hi, I have issue of build the first example

### ISSUE THREAD

**Issue by xiongzhend** [substrate-developer-hub/substrate-node-template#201]
I just follow the 1st tutorial and can't build it, please help me.

1. git clone -b v3.0.0+monthly-2021-05 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
2. cd substrate-node-template
3. cargo build --release

then I got this,

`error: failed to download `parity-db v0.2.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/xiongzhend/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-db-0.2.3/Cargo.toml`

Caused by:
  failed to parse the version requirement `0.11	` for dependency `parking_lot`

Caused by:
  expected comma after minor version number, found '\t'`

**Comment by NukeManDan** [comment]
Are you on windows? It may be related to issues there. If so, using WSL2 is suggested: https://substrate.dev/docs/en/knowledgebase/getting-started/

I am on Ubuntu using today's nightly and latest stable toolchain and cannot reproduce this 😢 (ran a `cargo clean` first)

**Comment by xiongzhend** [comment]
oh, I am using macosx, surprisely I viist crates.io and figure out pairity-db-0.2.3 is updated to 0.2.4, so I update the  Cargo.lock file and it works!

**Comment by NukeManDan** [comment]
`cargo update -p foo --precise 1.2.3` is best to use for this next time. Glad you solved it!

**Comment by Mahesh1** [comment]
had the same issue. following the tutorial of "creating first substrate chain". got the template using `git clone -b v3.0.0+monthly-2021-05 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
` but did `cargo update -p parity-db` & its building now

**Comment by tansaku** [comment]
I had the same - do the docs need updating? (not sure where they are) or the underlying code that's being checked out at this point?

**Comment by gilescope** [comment]
I'll update the tutorial

**Comment by gilescope** [comment]
@tansaku which url were you following? It's should work nicely with `v3.0.0+monthly-2021-08`.

**Comment by tansaku** [comment]
Here's the error I got from v3.0.0+monthly-2021-05:

```
❯ git clone -b v3.0.0+monthly-2021-05 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
...

❯ cd substrate-node-template
❯ cargo build --release
error: failed to download `parity-db v0.2.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/samueljoseph/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-db-0.2.3/Cargo.toml`

Caused by:
  failed to parse the version requirement `0.11	` for dependency `parking_lot`

Caused by:
  expected comma after minor version number, found '\t'
  ```

but I see you've updated the tutorial to use `git clone -b latest --depth 1 https://github.com/substrate-developer-hub/substrate-node-template` so all good I think.  I got things working a couple of weeks back via:

```
❯ cargo update -p parity-db
    Updating crates.io index

    Updating parity-db v0.2.3 -> v0.2.4
❯ 
```
