### ISSUE TITLE
How use get_account_id_from_seed from /node/src/chain_spec.rs

### ISSUE THREAD

**Issue by zababurinsv** [substrate-developer-hub/substrate-node-template#203]
I want change default account address in custom chain spec.

* I generate address from command
```
subkey generate --scheme sr25519
subkey inspect --scheme ed25519 "infant salmon buzz patrol maple subject turtle cute legend song vital leisure"
```

* In ` /node/src/chain_spec.rs` i wrote address 

```
vec![
    get_account_id_from_seed::<sr25519::Public> 
    ("0x112503550f30a4d5d......"),
],
```
* node:compile

*  ``` chain/target/release/node-template build-spec --disable-default-bootnode --chain dev > spec/customSpec.json ```

And in palletAura and palletGrandpa i dont get addrees  what i generated in before. 

```
   "palletAura": {
        "authorities": [
          "5GrwvaEF5zX....."
        ]
      },
      "palletGrandpa": {
        "authorities": [
          [
            "5FA9nQDVg2.....",
            1
          ]
        ]
      },
```
What seed phrase should I insert in `chain_spec.rs`  to get the same address in the chain Spec as after the command ?
```
subkey generate --scheme sr25519
subkey inspect --scheme ed25519 "infant salmon buzz patrol maple subject turtle cute legend song vital leisure"
```

**Comment by NukeManDan** [comment]
I am a bit confused. Why do you want to do this?
https://substrate.dev/docs/en/knowledgebase/advanced/cryptography#sr25519

Are you not wanting the improved signature type?

**Comment by NukeManDan** [comment]
Also, I ask you to please ask general substrate use questions in
- https://stackoverflow.com/questions/tagged/substrate (best)
- https://github.com/paritytech/subport/issues (if you don't want to use SO)
moving forward 🙏🏼

**Comment by zababurinsv** [comment]
I have a problem with this.

[("// {}", seed)](https://github.com/substrate-developer-hub/substrate-node-template/blob/fc9d24c429d271ec7d4f5075b8a7ec700c721a87/node/src/chain_spec.rs#L19)


For alice's account
```
get_account_id_from_seed :: <sr25519 :: Public> ("Alice")
```
I get the address `//alice`

For phrase
get_account_id_from_seed :: <sr25519 :: Public> ("knock version stumble fox stable sing forum blue unknown query marble evidence"),

I was getting the key
"//knock version stumble fox stable sing forum blue unknown query marble evidence"

**Comment by NukeManDan** [comment]
right, so with the seed phrase you actually want to use this: https://github.com/substrate-developer-hub/substrate-node-template/blob/fc9d24c429d271ec7d4f5075b8a7ec700c721a87/node/src/chain_spec.rs#L27

The **derivation path** "//Alice" is based on the well known seed: https://substrate.dev/docs/en/knowledgebase/integrate/subkey#well-known-keys -- with no seed set, the well known one is used by default with any path added.
