### ISSUE TITLE
about docker volumes bind

### ISSUE THREAD

**Issue by saintfeng** [substrate-developer-hub/substrate-node-template#206]
an issue mentioned before.
I think this issue needs a quick fix. 
about docker volumes bind, in file "docker-compose.yml", there's a meaningless bind of ".local" that caused this failure.

_**I just tried using this script for the first time and was able to get it working but I had to create a folder named `.local` first. 

_Originally posted by @danforbes in https://github.com/substrate-developer-hub/substrate-node-template/issues/84#issuecomment-696391757_**_

**Comment by NoCtrlZ** [comment]
Same issue and it will be fixed with merging following PR.
https://github.com/substrate-developer-hub/substrate-node-template/pull/189

**Comment by NukeManDan** [comment]
Merged - sorry for the delay on that 😅
