### ISSUE TITLE
Is runtime sequential influence blocking time?

### ISSUE THREAD

**Issue by zikunfan** [substrate-developer-hub/substrate-node-template#21]
Hi @JoshOrndorff ,
I aware that the `construct_runtime!` macro will construct a tuple named `AllModules`, and it will execute code by [specific sequential](https://intellipaat.com/community/12499/what-order-is-oninitialize-invoked-across-different-modules-in-a-substrate-runtime).

So should I aware sequential inside `construct_runtime!`?

**Comment by zikunfan** [comment]
I aware that `Session` module should be in front of `Grandpa`, or it leads to unstable block authoring time?

**Comment by JoshOrndorff** [comment]
I believe the `on_initialize` blocks are run in the order they appear in `construct_runtime!` with the exception that `system` is always run first. In my experience I haven't had to worry about that, but perhaps you may depending on your situation.

> That's surprising because grandpa had to do with block finalization, not block authoring. But if you can reproduce that finding, it should be an issue on the main substrate repository.
