### ISSUE TITLE
Add several storage example in substrate-node-template

### ISSUE THREAD

**Issue by branciard** [substrate-developer-hub/substrate-node-template#214]
**Motivation**

I try to add basic HashMap in FRAME v2 syntax in the new substrate-node-template

https://substrate.dev/docs/en/knowledgebase/runtime/storage#declaring-storage-items

like 

```
#[pallet::storage]
pub(super) type SomeComplexValue<T> = StorageValue<_, T::AccountId, ValueQuery>;
```

But I have error : 
```
associated type `AccountId` not found
```
It certainly easy to fix, but I search in others examples and substrate code but do not find how to fix it.

**Suggested Solution**

add all storage examples described here https://substrate.dev/docs/en/knowledgebase/runtime/storage#declaring-storage-items
in the substrate-node-template lib.rs example

**Alternatives**
At least add commented storage example lines. For a copy/paste usage.

**Comment by sacha-l** [comment]
Thank you @branciard for creating [this how-to guide](https://substrate.dev/substrate-how-to-guides/docs/pallet-design/storage-map) to address this issue. Closing this now.
