### ISSUE TITLE
error librocksdb-sys v6.17.3

### ISSUE THREAD

**Issue by PhuongHoang1182** [substrate-developer-hub/substrate-node-template#216]
How can I fix this issue. I'm install on a PC win 10 

error: failed to run custom build command for `librocksdb-sys v6.17.3`
![image](https://user-images.githubusercontent.com/30220537/125616351-98ce89ba-794a-4a44-b83b-b902e34ba14b.png)

**Comment by NukeManDan** [comment]
You are missing dependencies set out in the instructions here: https://substrate.dev/docs/en/knowledgebase/getting-started/windows-users

I would highly recommend using WSL2 as it will save a lot of headache like this moving forward
