### ISSUE TITLE
`error[E0609]: no field `__rip` on type `__darwin_arm_thread_state64``

### ISSUE THREAD

**Issue by garrettmaring** [substrate-developer-hub/substrate-node-template#218]
**Description**

After running the Rust setup and calling `$ cargo run --release -- --dev --tmp` the project fails to build.

**Steps to Reproduce**

Go through template rust setup instructions and then run `cargo run --release -- --dev --tmp`

**Expected vs. Actual Behavior**

The node to run

**Environment**

macOS (M1) Big Sur 11.3.1

Default host: aarch64-apple-darwin
rustup home:  /Users/.../.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.53.0 (53cb7b09b 2021-06-17)

**Comment by garrettmaring** [comment]
It looks like if I freshly clone this template it works. What dependencies need to upgrade for projects that used an older version of the template?

**Comment by NukeManDan** [comment]
#213 and #179  are related. - for M1 in particular there are workarounds, best practice is to update to the latest release 🙏🏼 I am not sure of the exact upstream substrate deps fixed this specific issue.
