### ISSUE TITLE
Facing runtime error while implementing assets pallet (1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter)

### ISSUE THREAD

**Issue by aramakam3505** [substrate-developer-hub/substrate-node-template#220]
**Question**
**Facing runtime error while implementing assets pallet (1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter)**
### **More info about error:-**
1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: Some(Error { cause: Some(Error { cause: None, desc: "Not enough data to fill buffer" }), desc: "Could not decode Call::create.2" }), desc: "Could not decode Call::Assets.0" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: Some, Error { cause: Some, Error { cause: None, desc: "Not enough data to fill buffer" }, desc: "Could not…
### **The changes i have made** 
1.After cloning monthly-2021-07(latest version of substrate-node-template)
2. Implemented assets pallet with below code

**_cargo.toml:-_**
'pallet-assets/std',

[dependencies.pallet-assets]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-07'
version = '3.0.0'

**_lib.rs:-_**
parameter_types!{
    pub const StringLimit: u32 = 50;
    pub const MetadataDepositBase: Balance = 2 * DOLLARS ;
    pub const MetaDataDepositPerByte: Balance = 2 * DOLLARS ;
    //pub const AssetDepositBase: Balance = 2;
    pub const AssetDepositPerZombie: Balance = 2 * DOLLARS;
    pub const AssetDeposit: Balance = 2 * DOLLARS ;
    pub const ApprovalDeposit: Balance = 2 * DOLLARS ;
}

impl pallet_assets::pallet::Config for Runtime {
    // The ubiquitous event type.
    type Event= Event;
    type Balance= Balance;
    type AssetId= u32;
    type Currency = Balances;
    type ForceOrigin = EnsureRoot<AccountId>;
    type AssetDeposit = AssetDeposit;
    type ApprovalDeposit = ApprovalDeposit;
    type StringLimit = StringLimit;  
    //type AssetDepositBase=AssetDepositBase;
    //type AssetDepositPerZombie= AssetDepositPerZombie;
    type MetadataDepositBase = MetadataDepositBase;
    type MetadataDepositPerByte = MetaDataDepositPerByte;
    type Freezer = ();
    type Extra = ();
    type WeightInfo = pallet_assets::weights::SubstrateWeight<Runtime>;
  }

**The solutions I have got through stackoverflow are:-**
_It is best to match the dependencies of Polkadot for substrate, typically that is the master branch of substrate._
In substrate(inside node codebase)they have used 4.0.0 version of assets pallet ....  If i give that i am getting some internal dependencies errors and i have tried to change all pallets version to 4.0.0. It didnt work.
If possible please provide correct implementation of the assets-pallet and cargo.toml file.

**Comment by aramakam3505** [comment]
@NukeManDan need your help.

**Comment by NukeManDan** [comment]
Not all substrate deps are the same version, as you can see in the `Cargo.toml` files for the pallets themselves. I would encourage using the deps Polkadot uses if you want to be compatible with the latest API. There are notes on compatibility in the releases: 
https://github.com/polkadot-js/api/releases/
https://github.com/paritytech/polkadot/releases/

If you are running into build errors, I suggest using the node template to test at a specific release throughout for all pallets, and a released API close to when this was released as well to test.

**Comment by NukeManDan** [comment]
If you have more issues, use https://github.com/paritytech/subport/issues
