### ISSUE TITLE
cargo test fails

### ISSUE THREAD

**Issue by gshep** [substrate-developer-hub/substrate-node-template#224]
**Question**

Hi! I've encountered something strange with tests. If pallet_balances added to Test runtime and its `Config<T>` included then `cargo test` may fail. For diff see this PR - https://github.com/gshep/substrate-node-template/pull/1/files

1. if `cargo test --lib -p pallet-template -p node-template` or `cargo test --lib -p pallet-template -p node-template-runtime` run in the workspace root then everthing compiled successfully and tests are executed
2. if `cargo test --lib -p pallet-template` run in the workspace root (or just `cargo test` in the `${workspace}/pallets/template`) then I got the following error:
```
   Compiling pallet-template v3.0.0 (/home/user/devel/substrate/substrate-node-template/pallets/template)
error[E0412]: cannot find type `GenesisConfig` in crate `pallet_balances`
  --> pallets/template/src/mock.rs:14:1
   |
14 | / frame_support::construct_runtime!(
15 | |     pub enum Test where
16 | |         Block = Block,
17 | |         NodeBlock = Block,
...  |
23 | |     }
24 | | );
   | |__^ not found in `pallet_balances`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
   |
1  | use crate::mock::system::GenesisConfig;
   |
1  | use frame_system::GenesisConfig;
   |

error[E0283]: type annotations needed
  --> pallets/template/src/mock.rs:14:1
   |
14 | / frame_support::construct_runtime!(
15 | |     pub enum Test where
16 | |         Block = Block,
17 | |         NodeBlock = Block,
...  |
23 | |     }
24 | | );
   | |__^ cannot infer type
   |
   = note: cannot satisfy `_: std::default::Default`
   = note: required by `std::default::Default::default`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0283, E0412.
For more information about an error, try `rustc --explain E0283`.
error: could not compile `pallet-template`

To learn more, run the command again with --verbose.
```

Am I missing something? Could someone explain this behavior? Thanks in advance!

**Comment by NukeManDan** [comment]
At first glance, I think your mock runtime is missing a `use pallet_balances` line? and `[dev-dependencies.pallet-balances]` likely needs to be a normal dep?

Further I don't know what you are trying to do here. Use the balances pallet coupled to the template? https://substrate.dev/recipes/pallet-coupling.html will help you there. I see no reason to only include the ballet in a mock runtime

**Comment by gshep** [comment]
pallet_template may use `Currency` trait, for example. And intention is to test the pallet with the mock runtime and enabled pallet_balances as the latter provides `Currency` implementation.

pallet_template doesn't depend directly on pallet_balances nor has to couple with it. So the answer is no, pallet_balances doesn't need to be a normal dep. Also there are similar usage of balances in tests, for example in official pallet_contracts - https://github.com/paritytech/substrate/blob/v3.0.0/frame/contracts/Cargo.toml

**Comment by gshep** [comment]
it is the issue in cargo - https://github.com/rust-lang/cargo/issues/4463
