### ISSUE TITLE
mac build fail, failed to run custom build command for  node-template-runtime v3.0.0

### ISSUE THREAD

**Issue by liuhuanhui** [substrate-developer-hub/substrate-node-template#226]
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Ram 16 GB 3733 MHz LPDDR4X

Intel Iris Plus Graphics 1536 MB
OS：	macOS 10.15.6 (19G73)

![image](https://user-images.githubusercontent.com/10370625/128729645-1a841eee-6b6a-4b31-a848-e079c0f86e36.png)

**Comment by NukeManDan** [comment]
As the error says, you need to install rust nightly.

See the guide for more: https://substrate.dev/docs/en/knowledgebase/getting-started/
