### ISSUE TITLE
Update docker compose, and run scripts

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-node-template#236]
#212 is older, but reveals that the docker integrations are likely stale and broken. We should either remove these, or update - ideally tested in CI here as well. Possibly there is some upstream tooling we can use for this? As the template is used upstream already for the release pipeline IIUC.

**Comment by kamikazebr** [comment]
Maybe close that merged issue?

**Comment by koslib** [comment]
IMO a docker/docker-compose based setup is much needed. Not everyone has a local working Rust setup, neither should be required to. Offering a working out-of-the-box docker-based solution is a must.

**Comment by NukeManDan** [comment]
#235 was not a fix. I simply have not checked the docker functionality - open to have others give it a test, I suspect there few changes (if any) needed for `latest`
reference: https://github.com/paritytech/substrate/tree/master/docker

**Comment by muddlebee** [comment]
@NukeManDan can I pick this up??
I had a hard time setting this project manually from installing rust till all :P should give this a go..

**Comment by NukeManDan** [comment]
Sure!! @muddlebee I would say we have you update things here, but really they should land upstream in substrate itself, so please open a PR here, and @ me but expect to migrate upstream once in a good place. Feel free to DM me https://matrix.to/#/@dan.shields:matrix.parity.io if you need anything along the way :rocket:

**Comment by georgiosd** [comment]
```
PS C:\Users\georgiosd\Documents\substrate-node-template> docker-compose -f .\docker-compose.yml up
Starting node-template ... done
Attaching to node-template
node-template | error: failed to parse manifest at `/var/www/node-template/node/Cargo.toml`
node-template |
node-template | Caused by:
node-template |   failed to parse the `edition` key
node-template |
node-template | Caused by:
node-template |   this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
node-template exited with code 101
``` 

Any ideas? :)

**Comment by NukeManDan** [comment]
Any changes to the source on this repo should be made upstream https://github.com/paritytech/substrate/tree/master/bin/node-template :pray:
