### ISSUE TITLE
Use Substrate v3.0.0 to Build a permissioned network has some errors

### ISSUE THREAD

**Issue by chusanchen** [substrate-developer-hub/substrate-node-template#237]
I followed the Tutorials   [https://substrate.dev/docs/en/tutorials/build-permission-network/](url)
But there are some difference between the Tutorials and my documents
**1**. in  **runtime/Cargo.toml**
I defined pallet-node-authorization  using the following code
`[dependencies.pallet-node-authorization]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-08'
version = '4.0.0-dev'`

**2.**  in  **runtime/src/lib.rs**
 I have to replace **Module** with **Pallet**  in construct_runtime!
NodeAuthorization: pallet_node_authorization::{Pallet, Call, Storage, Event<T>, Config<T>},

**3.**  in **node/src/chain_spec.rs**   my document has two  **GenesisConfig**   
**This is different from the Tutorials**  
Below is the source code
`fn testnet_genesis(
	wasm_binary: &[u8],
	initial_authorities: Vec<(AuraId, GrandpaId)>,
	root_key: AccountId,
	endowed_accounts: Vec<AccountId>,
	_enable_println: bool,
) -> GenesisConfig {
     GenesisConfig {
		pallet_node_authorization: Some(NodeAuthorizationConfig {
			nodes: vec![
				(
					OpaquePeerId(bs58::decode("12D3KooWCYhefJ57H4PDRDiEJGaqQJA48Jvj7FFz6LeZt9Ju9ULT").into_vec().unwrap()),
					endowed_accounts[0].clone()
				),
				(
					OpaquePeerId(bs58::decode("12D3KooWNwXK75jcgfdxfbSvg3tHMKr9brnigoQKWLZffGReMWxK").into_vec().unwrap()),
					endowed_accounts[1].clone()
				),
			],
		}),
		system: SystemConfig {
			// Add Wasm runtime to storage.
			code: wasm_binary.to_vec(),
			changes_trie_config: Default::default(),
		},
		balances: BalancesConfig {
			// Configure endowed accounts with initial balance of 1 << 60.
			balances: endowed_accounts.iter().cloned().map(|k| (k, 1 << 60)).collect(),
		},
		aura: AuraConfig {
			authorities: initial_authorities.iter().map(|x| (x.0.clone())).collect(),
		},
		grandpa: GrandpaConfig {
			authorities: initial_authorities.iter().map(|x| (x.1.clone(), 1)).collect(),
		},
		sudo: SudoConfig {
			// Assign network admin rights.
			key: root_key,
		},
	}`
4.in ` runtime/src/lib.rs`    I replace `Trait` with `Config`    Below is the source code
`impl pallet_node_authorization::Config for Runtime {
    type Event = Event;
    type MaxWellKnownNodes = MaxWellKnownNodes;
    type MaxPeerIdLength = MaxPeerIdLength;
    type AddOrigin = EnsureRoot<AccountId>;
    type RemoveOrigin = EnsureRoot<AccountId>;
    type SwapOrigin = EnsureRoot<AccountId>;
    type ResetOrigin = EnsureRoot<AccountId>;
    type WeightInfo = ();
}
`
After i execute  **cargo build --release**    The following is the error message

**sanc@ubuntu:~/substrate-node-template/node/src$cargo build --release
   Compiling node-template v3.0.0-monthly-2021-08 (/home/sanc/substrate-node-template/node)
error[E0560]: struct `GenesisConfig` has no field named `pallet_node_authorization`
   --> node/src/chain_spec.rs:137:3
    |
137 |         pallet_node_authorization: Some(NodeAuthorizationConfig {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^ help: a field with a similar name exists: `node_authorization`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0560`.
error: could not compile `node-template`

To learn more, run the command again with --verbose.**

**Comment by chusanchen** [comment]
When i execute  **cargo build --release**  in  **sanc@ubuntu:~/substrate-node-template**  there are some errors
[http://a1.qpic.cn/psc?/V1062p041bLzMO/bqQfVz5yrrGYSXMvKr.cqaFXXCFoRh5TMF5EYnwSk0fkjt9*wDDAkJ.ydD1sRYvxVoqlEZEoNRPL*zKnXXyX9d46j.6syUPh6vdM61JzPew!/b&ek=1&kp=1&pt=0&bo=sAP5ALAD.QADEDU!&tl=1&su=0176292447&tm=1631257200&sce=0-12-12&rf=2-9](url)

When i execute  **cargo build --release**  in  **sanc@ubuntu:~/substrate-node-template/runtime**    Compile pass
[http://a1.qpic.cn/psc?/V1062p041bLzMO/bqQfVz5yrrGYSXMvKr.cqUTwiurNR24BJuTL97rQ*lPWRzCxWiaY51bpTOM.6FLwvXai6JQ025rFCbtAGcH3vDIenDR6e7N88grIRMMfMQo!/b&ek=1&kp=1&pt=0&bo=rAJGAKwCRgADEDU!&tl=1&su=0241941519&tm=1631257200&sce=0-12-12&rf=2-9](url)

I am curious why this is ?  thank u very much

**Comment by NukeManDan** [comment]
you must use the same version of substrate in all deps. Use the base node template you need for this and add deps `tag = 'monthly-2021-08' version = '4.0.0-dev'` seems like what you are after? I recommend `tag = 'monthly-2021-09+1' version = '4.0.0-dev'` instead.

**Comment by NukeManDan** [comment]
Still need help? Let me know, we can reopen this issue :pray:
