### ISSUE TITLE
WebSocket connection to block explorer is blocked.

### ISSUE THREAD

**Issue by tifrel** [substrate-developer-hub/substrate-node-template#238]
**Description**

I am currently doing your [Private Network tutorial](https://substrate.dev/docs/en/tutorials/start-a-private-network/alicebob), and the locally hosted explorer cannot connect to the running node.

**Steps to Reproduce**

1. Run the node as shown in the Tutorial
2. Host the [Polkadot Explorer](https://github.com/polkadot-js/apps) locally, using Docker.
3. Try open `localhost:80`

**Expected vs. Actual Behavior**

Expected behavior would be as shown in the tutorial, but what I get is:

```
2021-09-14 12:12:59 Accepted a new tcp connection from 127.0.0.1:63407.
2021-09-14 12:12:59 Blocked connection to WebSockets server from untrusted origin: Some("http://localhost")
```

The explorer keeps increasing the port number, giving me another pair of Accepted/Blocked messages. The `Some(...)` message hints to me that the problem is occuring somewhere in the Rust codebase, aka the node, however I cannot find the string when grepping the repo.

**Environment**

- Operating system: macOS Big Sur 11.3.1
- Template version/tag: v3.0.0+monthly-2021-09+1
- Rust version:
  - stable-aarch64-apple-darwin, rustc 1.55.0 (c8dfcfe4 2021-09-06)
  - nightly-aarch64-apple-darwin, rustc 1.57.0-nightly (d69fe5726 2021-09-10)
- Docker Desktop: 4.0.0.12
- Container id: 08146b8cb2a2 ()
- Tried Firefox 92.0 and Safari 14.1

**Logs, Errors or Screenshots**

See above.

**Additional information**

Probably the same, yet closed and unresolved issue is #193 .

**Comment by NukeManDan** [comment]
This is to use a locally running apps UI? (What you are calling "explorer")

IIRC you need to use the loopback address: 127.0.0.1
Does that work as expected? The behavior is expected (I think) for `localhost` to be seen as different than that IP. 

Any CORS request needs flags and a proper SSL setup: https://wiki.polkadot.network/docs/maintain-wss
you may need node flags:
```
        --unsafe-rpc-external              
            Listen to all RPC interfaces.
            
            Same as `--rpc-external`.
        --unsafe-ws-external               
            Listen to all Websocket interfaces.
            
            Same as `--ws-external` but doesn't warn you about it.
```

**Comment by tifrel** [comment]
None of those worked. `--rpc-cors all` does the trick however.
