### ISSUE TITLE
v2 ready ?

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-node-template#24]
is this whole repo ready for v2 ?

OR can these these instructions "[Advanced: Generate Your Own Substrate Node Template](https://github.com/substrate-developer-hub/substrate-node-template#advanced-generate-your-own-substrate-node-template)" be used to generate my own node template on the basis of the (substrate.dev recommended) [pre-v2.0-3e65111](https://github.com/paritytech/substrate/tree/3e651110aa06aa835790df63410a29676243fc54)   ?

OR ...

**Comment by JoshOrndorff** [comment]
This repo currently uses the same pre-v2.0-3e65111 you referenced. You can confirm that for yourself by looking in the `Cargo.toml` file and seeing lines like [this one](https://github.com/substrate-developer-hub/substrate-node-template/blob/8b6fe6666d589486dd541663a32ffd98f2e21d74/Cargo.toml#L17).

```
rev = '3e651110aa06aa835790df63410a29676243fc54'
```

If you want something even newer, I might recommend the very-recently released alpha.1 You can generate that node template by following the instructions you linked.

**Comment by drandreaskrueger** [comment]
perfect, thanks!
