### ISSUE TITLE
Start a Private Network

### ISSUE THREAD

**Issue by jnahjskncvjkxhfvdjsnfvjk** [substrate-developer-hub/substrate-node-template#241]
When I finished following the tutorial, the Alice node produced no blocks.I've tried many times,what are the possible causes of the problem？

**Comment by NukeManDan** [comment]
Likely you have not set the keys correctly. Sometimes you need to restart nodes for the keys to be picked up. 
Try using the solution's scripts to make it easier?
https://substrate.dev/docs/en/tutorials/start-a-private-network/customchain#solutions-and-helpers
https://github.com/substrate-developer-hub/substrate-node-template/tree/tutorials/solutions/private-chain-v3/key-insert
