### ISSUE TITLE
Crash when starting 2 nodes

### ISSUE THREAD

**Issue by Dinonard** [substrate-developer-hub/substrate-node-template#242]
**Description**

No changes made to the template.
I started with the Substrate academy and followed instructions to start 2 nodes.
A crash occurs when starting the second one.

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

1. Build the release on tag v3.0.0+monthly-2021-09+1 
2. cargo run -- --base-path data/node1 --chain local --alice --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --name validator-alice --validator
3. cargo run -- --base-path data/node2 --chain local --bob --port 30334 --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --name validator-bob --validator
4. Crash happens

A huge stack-trace + this message at the end (sorry, I didn't save the entire backtrace):
Thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/dino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/shutdown.rs:51

**Expected vs. Actual Behavior**

When I reverted back to 3.0.0+monthly-2021-08, everything worked well.

**Comment by NukeManDan** [comment]
I put in a ticket upstream to fix this, presently we insist you manually configure non-conflicting ports on your machine. 
https://github.com/paritytech/substrate/issues/9832

**Comment by Dinonard** [comment]
Hey Dan,

thanks for the reply and the solution!

I actually did run the release build, I just copy/pasted the commands from the lecture.
My mistake, sorry for wasting your time! 😶
