### ISSUE TITLE
Remove `v3.0.0+` in our monthly tag

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-node-template#250]
Because most pallets inside are no longer `v3.0.0`, but `v4.0.0-dev`.
There is also no `v3.0.0+..` in the upstream Substrate repo.

Address this after `docs.substrate.io` launch.

**Comment by NukeManDan** [comment]
I would move to version the _packages_ in the template (upstream and here) to the "base" version of substrate we use as a dependency. Would that make sense? 

So all `Cargo.toml` (node, runtime, pallet) package version would be `3.0.0` or whatever matched the tags we use from the substrate release. And thus any tags derived from this would include the "right" version to be implied by consumers of the template.
