### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Manuelandro** [substrate-developer-hub/substrate-node-template#252]
**Description**

I tried three times to clone the repo from scratch and build it but at some point i get this error:

`error: failed to run custom build command for node-template-runtime v3.0.0-monthly-2021-10 (/Users/manuelpalma/substrate-node-template/runtime)
Rust nightly not installed, please install it!
`

But i followed the documentation which does not mention to install rust nightly 

**Expected vs. Actual Behavior**

Should build

**Environment**

- Operating system: macOs 11.4 (not a m1 chip!)
- Template version/tag: latest
- Rust version (run `rustup show`):  stable-x86_64-apple-darwin (default) / rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Logs, Errors or Screenshots**

`Compiling node-template-runtime v3.0.0-monthly-2021-10 (/Users/manuelpalma/substrate-node-template/runtime)
error: failed to run custom build command for node-template-runtime v3.0.0-monthly-2021-10 (/Users/manuelpalma/substrate-node-template/runtime)
Caused by:
  process didn't exit successfully: /Users/manuelpalma/substrate-node-template/target/release/build/node-template-runtime-f19cbb00b7e18ad0/build-script-build (exit status: 1)
  --- stderr
  Rust nightly not installed, please install it!
warning: build failed, waiting for other jobs to finish...`

**Comment by NukeManDan** [comment]
Sorry you struggled here! You must have missed the install guide: https://substrate.dev/docs/en/knowledgebase/getting-started/

You require nightly to build Wasm in Substrate. Was that not obvious in the README? or how did you go about trying to find the issue with your problem here?

**Comment by NukeManDan** [comment]
This might help others next time: https://github.com/substrate-developer-hub/substrate-node-template/pull/253
