### ISSUE TITLE
How to rename the template?

### ISSUE THREAD

**Issue by readlnh** [substrate-developer-hub/substrate-node-template#26]
Is there a script to rename the template as before?

**Comment by readlnh** [comment]
I rename the template manually, when I interact with the node using polka.js, it report:
```
submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution(Wasmi(Trap(Trap { kind: Unreachable }))): RuntimeApi("Execution(Wasmi(Trap
```

**Comment by JoshOrndorff** [comment]
There isn't a rename script anymore. There are several things that you may want to rename about the template.

* Info the node prints on startup https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/src/main.rs#L12-L19
* Name of the crate https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/Cargo.toml#L16
* Name of the binary that gets built https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/Cargo.toml#L21
* Name of the runtime https://github.com/substrate-developer-hub/substrate-node-template/blob/master/runtime/Cargo.toml#L6 Changing this will also require some changes elsewhere in the code. Search and Replace is a good way to go.

I'll try to help with your error, but I need more context. Which of these (or something else) did you change? Did the extrinsic work before the rename?

**Comment by readlnh** [comment]
Thank you for replying, I will try it again. Now I can't provide more information, but I remember the extrinsic work before the rename.

**Comment by readlnh** [comment]
I found out what's wrong with my projects. I changed the runtime version, however I didn't rebuild .wasm file. I remove the wbuild folder, then rebuild it, all things work. Thank you very much.
