### ISSUE TITLE
Move to `polkadot-x.x.x` releases?

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-node-template#260]
Related: [1](https://github.com/substrate-developer-hub/substrate-docs/issues/476) - [2](https://github.com/substrate-developer-hub/substrate-docs/issues/477)

We use monthly versioning for now, but the ecosystem is matching to the tune of Polkadot presently. Although this is _not_ a parachain template, it would be highly useful to have a solo-chain that was _compatible_ per release of Polkadot. 

Seems like an easy win... would we be missing anything special by doing this over monthly or master?
cc @gnunicorn @bkchr

**Comment by NukeManDan** [comment]
But the rest of the ecosystem is (primarily) targeting parachains, and this will help compatibility _a lot_ for the many 3rd parties that build pallets to integrate and such. 

It would also make the devhub versioning story uniform for everything (except frontier), making the load on maintenance a lot lighter.

**Comment by bkchr** [comment]
If you want to build a pallet, yes, you will currently then have a branch that uses the same polkadot branch. However, I don't see how this is related to the node-template here.

> It would also make the devhub versioning story uniform for everything (except frontier), making the load on maintenance a lot lighter.

I mean, in the end I don't care. If you see that this makes your life easier for now, then do it. This is probably the most important point here.

**Comment by NukeManDan** [comment]
I think it will make everyone's life easier :grin: 

The issue is with all our tutorials and how-to guides being used mixed and matched, all these need to have uniform versions to work out of the box. So it's much easier to have a uniform set of things to reference than insist users patch their versioning.

(long term I am 100% for the versioning of crates _within_ substrate, not the entire project except for major releases as a milestone (like 4.0.0)... and leaning into `cargo update` and good semver adherence to make this not really an issue to have a site wide commit specifically set for use in upstream deps :crossed_fingers: I _hope_ this would be a better flow... not sure TBH)

**Comment by NukeManDan** [comment]
This will be the new release schedule moving forward :rocket:
