### ISSUE TITLE
Stuck building `node-template-runtime`

### ISSUE THREAD

**Issue by m-cat** [substrate-developer-hub/substrate-node-template#262]
**Description**

Whenever I try to build `substrate-node-template` (branch `latest`), it gets stuck building `node-template-runtime`. My CPU goes back down as if the build was over but `cargo build` doesn't exit. I'm on a Mac.

**Steps to Reproduce**

1. Check out `latest` branch
2. Run `cargo check` or `cargo build`

**Expected vs. Actual Behavior**

Expected the build to complete successfully.

**Environment**

- Operating system: MacOS 11.6
- Template version/tag: `latest`
- Rust version (run `rustup show`): `rustc 1.56.1 (59eed8a2a 2021-11-01)`

**Logs, Errors or Screenshots**

```
Building [=======================> ] 903/907: node-template-runtime(build)
```

(Stuck on this step)

**Additional Information**

None

**Comment by NukeManDan** [comment]
how long do you wait? what is your machine spec: cpu detail & ram

**Comment by m-cat** [comment]
@NukeManDan I've waited for several hours before. Currently at an hour.

CPU: 2.4 GHz 8-Core Intel Core i9
RAM: 32 GB 2667 MHz DDR4

**Comment by NukeManDan** [comment]
try `cargo build --release--verbose` and share the logs in a gist or attached txt file here?

**Comment by m-cat** [comment]
@NukeManDan https://hackerpaste.hns.siasky.net/#fATctO9fHutCn3U3nVwGg8yVM7z2LnmkCffnX5AaKaui_Q8yO-fTq0RCeGqgEevoic

**Comment by NukeManDan** [comment]
I can't see anything obvious here, and think this is a rust compiler issue, I would ask you to open up an issue describing this and reference here :pray: 
https://github.com/rust-lang/rust
