### ISSUE TITLE
Is there community for substrate online chat?

### ISSUE THREAD

**Issue by andrewpedia** [substrate-developer-hub/substrate-node-template#263]
**Question**

**Comment by andrewpedia** [comment]
I have deploy node with --dev --tmp ,and the node is producing blocks .
my question is :  the node runs on local net , and  no transactions , so where is these blocks coming from ?

**Comment by sacha-l** [comment]
Hi @andrewpedia : a better place for these types of questions is our [community chat on Element](https://app.element.io/#/room/#substrate-technical:matrix.org). But to answer your question, the node template uses the Aura pallet which enables the network to act as a [proof of authority network](https://en.wikipedia.org/wiki/Proof_of_authority). The Grandpa pallet is what's responsible for block finality. Those two pieces are what enable block production and execution on a local machine.

**Comment by sacha-l** [comment]
Hope that helps answer your question. Congrats on making your node run ! Feel free to reopen this issue if there's anything else I can help with.

**Comment by andrewpedia** [comment]
@sacha-l   , thanks for reply !  btw , what do you mean by "block finality" ?

**Comment by andrewpedia** [comment]
And I do not find code for these two pallets under palette folder

**Comment by sacha-l** [comment]
Of course @andrewpedia - here are the links to the source code:
- [FRAME's Aura pallet](https://github.com/paritytech/substrate/tree/master/frame/aura)
- [FRAME's Grandpa pallet](https://github.com/paritytech/substrate/tree/master/frame/grandpa)

Any blockchain has different algorithms for finalizing blocks, i.e. determining which blocks will be part of the chain's history. [This is a good article](https://medium.com/polkadot-network/grandpa-block-finality-in-polkadot-an-introduction-part-1-d08a24a021b5) on how Grandpa does block finality for Substrate based blockchains.

**Comment by andrewpedia** [comment]
okay . thank  you .
I am confused that this node template seems only contains on pallet which is under  the pallet/template directory .
