### ISSUE TITLE
Benchmarks weights not actually used

### ISSUE THREAD

**Issue by apopiak** [substrate-developer-hub/substrate-node-template#267]
The template crate has a benchmarking module and is also included in the runtime, but there is not weights file and the `do_something` dispatchable does not use any generated weight.

**Comment by ggwpez** [comment]
Somehow when I try to run the benchmarks I get this error:  
```pre
error: 'compiled' isn't a valid value for '--wasm-execution <METHOD>'
[possible values: interpreted-i-know-what-i-do]
```
Try it with `cargo run --release --features runtime-benchmarks benchmark --execution wasm --wasm-execution compiled --chain dev --pallet "template" --extrinsic "" --steps 1 --repeat 1`.

**Comment by brunopgalvao** [comment]
+1 

I got the same error on OS X and Linux for `latest` tag. Works fine on `monthly-2021-12` tag

**Comment by NukeManDan** [comment]
#313 fixes this, and `latest` is now pushed to this commit 

```
cargo run --release --features runtime-benchmarks benchmark --execution wasm --wasm-execution compiled --chain dev --pallet "pallet-template" --extrinsic "" --steps 1 --repeat 1

ic '' --steps 1 --repeat 1`
Pallet: "pallet_template", Extrinsic: "do_something", Lowest values: [], Highest values: [], Steps: 1, Repeat: 1
Raw Storage Info
========
Storage: TemplateModule Something (r:0 w:1)

Median Slopes Analysis
========
-- Extrinsic Time --

Model:
Time ~=    22.38
    + s        0
              µs

Reads = 0 + (0 * s)
Writes = 1 + (0 * s)

Min Squares Analysis
========
-- Extrinsic Time --

Model:
Time ~=    22.38
              µs

Reads = 0
Writes = 1

```
