### ISSUE TITLE
change SS58Prefix error

### ISSUE THREAD

**Issue by bingryan** [substrate-developer-hub/substrate-node-template#275]
change [SS58Prefix](https://github.com/substrate-developer-hub/substrate-node-template/blob/master/runtime/src/lib.rs#L140) and [chain_spec Properties](https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/src/chain_spec.rs#L71)

```
pub const SS58Prefix: u16 = 1024;
```

The account prefix is changed, but when i  use [polkadot app](https://polkadot.js.org/apps/) transfer balance get an error

```
balances.transferKeepAlive
-32602: Invalid params: UnknownVersion.
```
![image](https://user-images.githubusercontent.com/41174435/144551495-0192bc44-3169-457f-be56-3ee66e02c917.png)

How to deal with it is correct, if I want to change to other SS58Prefix.

**Comment by btwiuse** [comment]
It happens when your ss58prefix is not found in this list https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json

**Comment by NukeManDan** [comment]
For testing, please use `42` and then when you move to production, request to be added to the list  https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json as @btwiuse suggests :bow:
