### ISSUE TITLE
this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions

### ISSUE THREAD

**Issue by NetGodFather** [substrate-developer-hub/substrate-node-template#279]
Download the code directly, and then run "cargo run --release - --dev --tmp" to return an error

Returns the following error: 

# cargo run --release -- --dev --tmp

info: syncing channel updates for 'nightly-2020-10-06-x86_64-apple-darwin'
info: latest update on 2020-10-06, rust version 1.49.0-nightly (a1dfd2490 2020-10-05)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
error: failed to parse manifest at `/Users/hezhiqun/Substrate/Pistis/node/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.

**Comment by zhping5678** [comment]
Hello, so how did you solve the question. My rust and cargo version is 1.59.0

**Comment by tinplayscode** [comment]
Hi, how do you resolve this?☺

**Comment by an4s911** [comment]
Same issue, how did you solve it?

**Comment by a13z** [comment]
same issue here and wondering how to solve it

**Comment by hp-wsp** [comment]
您好！您所发给我的信件已经收到。                                        王伟
