### ISSUE TITLE
missing crate node-primitives on crates.io for 2.0.0-alpha.5

### ISSUE THREAD

**Issue by brenzi** [substrate-developer-hub/substrate-node-template#28]
I just tried to migrate our node to 2.0.0-alpha.5 starting with a fresh node-template.
For my pallet test mock I use `use node_primitives::{AccountId, Signature};`

But that crate is not on crates.io.

Therefore I'm stuck migrating.

**Comment by brenzi** [comment]
same for `substrate-test-runtime-client`

**Comment by JoshOrndorff** [comment]
The `node_primitives` crate is for use specifically in the demonstration node that lives in the Substrate repo. This is evidenced by the fact that it lives in `bin/node/pirmitives`. The two imports you mentioned, [AccountId](https://substrate.dev/rustdocs/master/node_primitives/type.AccountId.html) and [Signature](https://substrate.dev/rustdocs/master/node_primitives/type.Signature.html) are both type aliases to things that are in the library part of the Substrate repo and _are_ published on crates.io.

This node template, makes the same type aliases directly in the runtime's `lib.rs` ([AccountId](https://github.com/substrate-developer-hub/substrate-node-template/blob/da88e4aa4fb273894460fe1499717ffb0b02960b/runtime/src/lib.rs#L51), [Signature](https://github.com/substrate-developer-hub/substrate-node-template/blob/da88e4aa4fb273894460fe1499717ffb0b02960b/runtime/src/lib.rs#L47)). If you're basing your node on this template, you can use those type aliases directly, or if you like having them in a separate crate, you can move them to their own crate. You could call that crate `node-primitives` and let it's context make it clear what node they are for or you could give it a name like `brenzis-node-primitives`. You can see polkadot also [follows this pattern](https://github.com/paritytech/polkadot/tree/master/primitives

**Comment by brenzi** [comment]
ok. but how about substrate-test-runtime-client? Where should I get `use test_client::AccountKeyring;` from? From `sp_keyring` I guess?

**Comment by JoshOrndorff** [comment]
TBH, I'm not nearly as familiar with that one. I guess maybe from here https://substrate.dev/rustdocs/master/sp_keyring/test/index.html

@gnunicorn is that right?

**Comment by gnunicorn** [comment]
@brenzi `node-*` are meant for the `substrate-node`-default-implementation only, are very opinionated and not suitable for reusability but part of the executable only. We are still discussing whether we eventually publish them on crates.io but for the time being (and probably 2.0 release), these won't be published there (as we can't and won't give the same semver stability guarantees for the binary).

That said, [what you are asking for](https://github.com/paritytech/substrate/blob/d477017fb655f71de6c952b7eb085866bd8f6f7f/bin/node/primitives/src/lib.rs#L23-L35) is literally something you can (and should) define yourself:

```

use sp_runtime::{
	generic, traits::{Verify, IdentifyAccount}, MultiSignature
};

/// Alias to 512-bit hash when used in the context of a transaction signature on the chain.
pub type Signature = MultiSignature;

/// Some way of identifying an account on the chain. We intentionally make it equivalent
/// to the public key of our transaction signing scheme.
pub type AccountId = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;
```
