### ISSUE TITLE
Can't build due to semver conflict in serde json

### ISSUE THREAD

**Issue by shirshak55** [substrate-developer-hub/substrate-node-template#282]
error: failed to select a version for `serde_json`.
    ... required by package `sc-cli v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-12#b6c1c1bc)`
    ... which satisfies git dependency `sc-cli` of package `frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-12#b6c1c1bc)`
    ... which satisfies git dependency `frame-benchmarking-cli` of package `node-template v4.0.0-dev (/home/quantum/Desktop/projects/delete_it/substrate-node-template/node)`
versions that meet the requirements `^1.0.71` are: 1.0.73, 1.0.72, 1.0.71

all possible versions conflict with previously selected packages.

  previously selected package `serde_json v1.0.68`
    ... which satisfies dependency `serde_json = "^1.0.59"` (locked to 1.0.68) of package `cargo_metadata v0.14.1`
    ... which satisfies dependency `cargo_metadata = "^0.14.1"` of package `substrate-wasm-builder v5.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-12#b6c1c1bc)`
    ... which satisfies git dependency `substrate-wasm-builder` of package `node-template-runtime v4.0.0-dev (/home/quantum/Desktop/projects/delete_it/substrate-node-template/runtime)`
    ... which satisfies path dependency `node-template-runtime` (locked to 4.0.0-dev) of package `node-template v4.0.0-dev (/home/quantum/Desktop/projects/delete_it/substrate-node-template/node)`

failed to select a version for `serde_json` which could resolve this conflict

**Comment by OAyomide** [comment]
i +1 this. i am having same issue.

**Comment by NukeManDan** [comment]
Try `cargo update -p sc-cli` and maybe try to update a few more deps manually, see if this builds
 I will patch hear and upstream if this works for you, lmk

**Comment by UmaMaquinaDeOndas** [comment]
This fix worked for me, thanks Dan.

**Comment by shirshak55** [comment]
closing it and seems to work after deps fixes
