### ISSUE TITLE
About memory growth

### ISSUE THREAD

**Issue by rustbomber** [substrate-developer-hub/substrate-node-template#291]
**Question**

When the node first started, it used 20M of memory, and it reached 50M the next day. I don't know if it will keep growing.
![image](https://user-images.githubusercontent.com/437330/147713169-5048e901-696c-40ee-9a5a-4d1b40937f84.png)

Additional : my machine is  Apple MBP with  macOS Mojave 10.14.6 (18G9323)

**Comment by NukeManDan** [comment]
The state is expected to grow over time, Use the Prometheus endpoint to reveal more insights https://docs.substrate.io/tutorials/v3/node-metrics/
