### ISSUE TITLE
Problem with storage declaration

### ISSUE THREAD

**Issue by sergpsu** [substrate-developer-hub/substrate-node-template#295]
Hello!
After updating to the latest node-template I cannot build it with my pallet anymore. I've described the problem here with more details [https://stackoverflow.com/questions/70607968/substrate-storage-declaration](https://stackoverflow.com/questions/70607968/substrate-storage-declaration)
Could anyone look at this?

**Comment by NukeManDan** [comment]
Let's keep support on that SO thread.
