### ISSUE TITLE
Dev network has 0 balance for all accounts on s390x architecture

### ISSUE THREAD

**Issue by mrihn** [substrate-developer-hub/substrate-node-template#311]
**Description**

I brought up a dev node with the following command:

./target/release/node-template --alice -d /tmp/alice --ws-external --rpc-external --rpc-cors all --dev

I confirmed that the node came up with the expected output messages:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/88684821/153972447-cf8c4acd-159d-406e-a516-83b0952469f5.png">

I was having trouble running transactions against the node, so I checked the account balances on polkadot-js-apps and saw that all of the predefined accounts had a balance of 0.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/88684821/153972705-019bde8b-e4b8-4d8e-a3be-57b9d2aaef90.png">

**Expected vs. Actual Behavior**

I expected some of the accounts to be configured with a certain amount of funds, as mentioned in the doc:
https://docs.substrate.io/tutorials/v3/create-your-first-substrate-chain/

**Environment**

I brought up the node in an Ubuntu 20.04 docker container.

```
# ./target/release/node-template --version                                     
node-template 4.0.0-dev-0fa9414-s390x-linux-gnu
```

```
# rustup show
Default host: s390x-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-s390x-unknown-linux-gnu (default)
nightly-s390x-unknown-linux-gnu

active toolchain
----------------

stable-s390x-unknown-linux-gnu (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```

**Additional Information**

NOTE: Since s390x is a Big Endian architecture, we ran into an issue when substrate pulled in Merlin as a dependency.
https://github.com/dalek-cryptography/merlin/issues/58

For now, we went ahead by commenting the code https://github.com/dalek-cryptography/merlin/blob/master/src/lib.rs#L9
substrate still compiled and we were able to launch.

/*
|
10 | / compile_error!(
11 | | r#"
12 | | This crate doesn't support big-endian targets, since I didn't
13 | | have one to test correctness on. If you're seeing this message,
14 | | please file an issue!
15 | | "#
16 | | );
| |__^
*/

We encountered a similar problem when we tried to run a similar test with Polkadot:
https://github.com/paritytech/subport/issues/235

**Comment by NukeManDan** [comment]
We are asking all support requests and questions like this move to stack exchange: https://substrate.stackexchange.com/ , where we finally may get a resolution... although I am not sure to be honest as if the architecture really is to blame, we don't have many that would be able to reproduce it AFAIK
