### ISSUE TITLE
After commit polkadot v.0.9.17

### ISSUE THREAD

**Issue by StringNick** [substrate-developer-hub/substrate-node-template#315]
After commit polkadot v.0.9.17, stop working vector encoding, when i use vec in pallet it always show error.
Simple use 
`	pub type Something<T> = StorageValue<_, Vec<u8>>;
`
Error on build

```
  --> pallets/template/src/lib.rs:30:12
   |
30 |     #[pallet::pallet]
   |               ^^^^^^ the trait `MaxEncodedLen` is not implemented for `Vec<u8>`
   |
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageValue<_GeneratedPrefixForStorageSomething<T>, Vec<u8>>`
```

As from substrate docs i am using sp-std
`	use sp_std::vec::Vec;
`
, before this update its working nicely (sp-core, sp-io, sp-runtime was 4.0.0-dev) now they are 5.0.0

**Comment by Liu-WeiHu** [comment]
I have this problem
```
ensure!(!Proofs::<T>::contains_key(&proof), Error::<T>::ProofAlreadyClaimed);
    |                                   ^^^^^^^^^^^^ function or associated item cannot be called on `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageProofs<T>, frame_support::Blake2_128Concat, Vec<u8>, (<T as frame_system::Config>::AccountId, <T as frame_system::Config>::BlockNumber), frame_support::pallet_prelude::ValueQuery>` due to unsatisfied trait bounds
```

**Comment by arturgontijo** [comment]
As pointed here:
https://substrate.stackexchange.com/questions/544/maxencodedlen-is-not-implemented-for-vecu8

We must use `BoundedVec<u8, T::MaxLength>` or add `#[pallet::without_storage_info]` to the `pub struct Pallet<T>(_);`.

**Comment by flipchan** [comment]
same problem here: https://github.com/flipchan/frontier-pallet-upstream

**Comment by NukeManDan** [comment]
@arturgontijo has the answer above :grin:
