### ISSUE TITLE
[REQ] Template for BABE and Staking

### ISSUE THREAD

**Issue by nasa8x** [substrate-developer-hub/substrate-node-template#320]
**Motivation**

Most blockchains have rewards and staking to incentivize the installation of validators, increasing the security of the network. So quite a few people will have a need to use the BABE and Staking template.

**Suggested Solution**

Currently, [substrate-stencil](https://github.com/kaichaosun/substrate-stencil) has developed this template, but maybe because the author is too busy, it has not been updated for a long time.
So I hope the Official develops this template and updates it regularly like this one.

Thank you!

**Comment by NukeManDan** [comment]
If you would like this to happen, please open a details issue, or better, a PR on the upstream template here: https://github.com/paritytech/substrate/tree/master/bin/node-template

IMHO _most_ builders are not building production chains with this template, but rather for testing mostly. And those that are confident in most things then move to parachain development by and large. Checkout: https://github.com/substrate-developer-hub/substrate-parachain-template/
