### ISSUE TITLE
Don't use default weights in the runtime

### ISSUE THREAD

**Issue by ggwpez** [substrate-developer-hub/substrate-node-template#327]
Analogous to https://github.com/paritytech/polkadot/pull/5091  

Instead of relying on the default weights from `frame_support`; copy in the weights files and use them.  
This way we encourage developers to benchmark their own weights and create a more future proof structure.

**Comment by NukeManDan** [comment]
this should be implemented on Substrate, not the devhub version of the template :pray: perhaps close this issue and open one upstream?

**Comment by ggwpez** [comment]
Gonna do it upstream instead.
