### ISSUE TITLE
failed to get frame-benchmarking as a dependency of package

### ISSUE THREAD

**Issue by MehranMazhar** [substrate-developer-hub/substrate-node-template#331]
**Description**
After pulling from the tutorials/solutions/add-a-pallet, The build process with cargo gives an error.

**Steps to Reproduce**
1. cargo build --release
2. See error

**Expected vs. Actual Behavior**
The build process is not complete.

**Environment**
- Operating system: Linux/Ubuntu
- Brach: tutorials/solutions/add-a-pallet
- Rust version : 1.24.3

**Logs, Errors or Screenshots**

error: failed to get `frame-benchmarking` as a dependency of package `node-template v4.0.0-dev (/home/ubuntu/source/repos/substrate-node-template/node)`

Caused by:
  failed to load source for dependency `frame-benchmarking`

Caused by:
  Unable to update https://github.com/paritytech/substrate.git?tag=devhub/latest#352c46a6

Caused by:
  object not found - no match for id (352c46a648a5f2d4526e790a184daa4a1ffdb3bf); class=Odb (9); code=NotFound (-3)

![Capture](https://user-images.githubusercontent.com/11898578/160229260-385add0b-1a9c-4848-8376-67355b1741c5.PNG)

**Comment by NukeManDan** [comment]
Update your lock file, the tag is moved from time to time. You can pull from upstream here as well.

**Comment by MehranMazhar** [comment]
What exactly should I do?
