### ISSUE TITLE
 warning: "jemalloc support for `x86_64-pc-windows-msvc` is untested"  error: failed to run custom build command for `tikv-jemalloc-sys v0.4.3+5.2.1-patched.2`

### ISSUE THREAD

**Issue by Xtrotrik** [substrate-developer-hub/substrate-node-template#333]
PS F:\substrate-node-template> cargo build --release
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.89
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling winapi v0.3.9
   Compiling serde v1.0.136
   Compiling serde_derive v1.0.136
   Compiling memchr v2.4.1
   Compiling log v0.4.14
   Compiling autocfg v1.1.0
   Compiling typenum v1.15.0
   Compiling jobserver v0.1.24
   Compiling libc v0.2.121
   Compiling pin-project-lite v0.2.8
   Compiling futures-core v0.3.21
   Compiling smallvec v1.8.0
   Compiling ppv-lite86 v0.2.16
   Compiling lazy_static v1.4.0
   Compiling scopeguard v1.1.0
   Compiling futures-io v0.3.21
   Compiling slab v0.4.5
   Compiling num_cpus v1.13.1
   Compiling once_cell v1.10.0
   Compiling futures-sink v0.3.21
   Compiling futures-task v0.3.21
   Compiling futures-channel v0.3.21
   Compiling futures-util v0.3.21
   Compiling anyhow v1.0.56
   Compiling pin-utils v0.1.0
   Compiling futures v0.1.31
   Compiling regex-syntax v0.6.25
   Compiling subtle v2.4.1
   Compiling byteorder v1.4.3
   Compiling getrandom v0.1.16
   Compiling opaque-debug v0.3.0
   Compiling cpufeatures v0.2.2
   Compiling parking_lot_core v0.8.5
   Compiling crunchy v0.2.2
   Compiling block-padding v0.2.1
   Compiling tinyvec_macros v0.1.0
   Compiling static_assertions v1.1.0
   Compiling base64 v0.13.0
   Compiling arrayref v0.3.6
   Compiling either v1.6.1
   Compiling windows_x86_64_msvc v0.32.0
   Compiling serde_json v1.0.79
   Compiling radium v0.7.0
   Compiling parking_lot_core v0.9.1
   Compiling signature v1.5.0
   Compiling libm v0.2.2
   Compiling itoa v1.0.1
   Compiling stable_deref_trait v1.2.0
   Compiling tap v1.0.1
   Compiling crc32fast v1.3.2
   Compiling funty v2.0.0
   Compiling arrayvec v0.7.2
   Compiling byte-slice-cast v1.2.1
   Compiling ryu v1.0.9
   Compiling crossbeam-utils v0.8.8
   Compiling convert_case v0.4.0
   Compiling adler v1.0.2
   Compiling zstd-safe v4.1.3+zstd.1.5.1
   Compiling hex v0.4.3
   Compiling fallible-iterator v0.2.0
   Compiling target-lexicon v0.12.3
   Compiling arrayvec v0.5.2
   Compiling keccak v0.1.0
   Compiling cranelift-codegen-shared v0.80.1
   Compiling rustc-hex v2.1.0
   Compiling rustc-hash v1.1.0
   Compiling wasmparser v0.81.0
   Compiling byte-tools v0.3.1
   Compiling opaque-debug v0.2.3
   Compiling paste v1.0.6
   Compiling fake-simd v0.1.2
   Compiling rustc-demangle v0.1.21
   Compiling constant_time_eq v0.1.5
   Compiling sp-std v4.0.0 (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.18#32a4fe01)
   Compiling parity-util-mem v0.11.0
   Compiling itoa v0.4.8
   Compiling bitflags v1.3.2
   Compiling more-asserts v0.2.2
   Compiling rayon-core v1.9.1
   Compiling arrayvec v0.4.12
   Compiling humantime v2.1.0
   Compiling nodrop v0.1.14
   Compiling ref-cast v1.0.6
   Compiling cpp_demangle v0.3.5
   Compiling wasmtime-cache v0.33.1
   Compiling parity-wasm v0.42.2
   Compiling wasmtime v0.33.1
   Compiling hash-db v0.15.2
   Compiling memory_units v0.3.0
   Compiling downcast-rs v1.2.0
   Compiling environmental v1.1.3
   Compiling async-trait v0.1.52
   Compiling dyn-clone v1.0.5
   Compiling base58 v0.2.0
   Compiling bytes v1.1.0
   Compiling unicode-segmentation v1.9.0
   Compiling fastrand v1.7.0
   Compiling fixedbitset v0.4.1
   Compiling fnv v1.0.7
   Compiling multimap v0.8.3
   Compiling futures-timer v3.0.2
   Compiling matches v0.1.9
   Compiling unicode-bidi v0.3.7
   Compiling spin v0.5.2
   Compiling untrusted v0.7.1
   Compiling percent-encoding v2.1.0
   Compiling data-encoding v2.3.2
   Compiling pin-project-internal v0.4.29
   Compiling bs58 v0.4.0
   Compiling ntapi v0.3.7
   Compiling void v1.0.2
   Compiling asn1_der v0.7.5
   Compiling httparse v1.6.0
   Compiling pkg-config v0.3.24
   Compiling vcpkg v0.2.15
   Compiling ucd-trie v0.1.3
   Compiling waker-fn v1.1.0
   Compiling cache-padded v1.2.0
   Compiling parking v2.0.0
   Compiling tower-service v0.3.1
   Compiling prometheus v0.13.0
   Compiling try-lock v0.2.3
   Compiling wasm-bindgen-shared v0.2.79
   Compiling httpdate v1.0.2
   Compiling event-listener v2.5.2
   Compiling linked-hash-map v0.5.4
   Compiling bumpalo v3.9.1
   Compiling ipnet v2.4.0
   Compiling heck v0.4.0
   Compiling quick-error v1.2.3
   Compiling sc-executor-wasmtime v0.10.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.18#32a4fe01)
   Compiling async-task v4.2.0
   Compiling scoped-tls v1.0.0
   Compiling cfg-if v0.1.10
   Compiling match_cfg v0.1.0
   Compiling wasm-bindgen v0.2.79
   Compiling atomic-waker v1.0.0
   Compiling ipconfig v0.2.2
   Compiling cpufeatures v0.1.5
   Compiling widestring v0.4.3
   Compiling nohash-hasher v0.2.0
   Compiling dtoa v0.4.8
   Compiling pin-project-lite v0.1.12
   Compiling hex_fmt v0.3.0
   Compiling parity-send-wrapper v0.1.0
   Compiling bimap v0.6.2
   Compiling tt-call v1.0.8
   Compiling libp2p-uds v0.30.0
   Compiling winapi-build v0.1.1
   Compiling glob v0.3.0
   Compiling base-x v0.2.8
   Compiling unsigned-varint v0.5.1
   Compiling rawpointer v0.2.1
   Compiling winapi v0.2.8
   Compiling ip_network v0.4.1
   Compiling minimal-lexical v0.2.1
   Compiling rustversion v1.0.6
   Compiling bindgen v0.59.2
   Compiling fs_extra v1.2.0
   Compiling iovec v0.1.4
   Compiling shlex v1.1.0
   Compiling peeking_take_while v0.1.2
   Compiling percent-encoding v1.0.1
   Compiling lazycell v1.3.0
   Compiling memmap2 v0.5.3
   Compiling camino v1.0.7
   Compiling snap v1.0.5
   Compiling semver v1.0.6
   Compiling semver-parser v0.7.0
   Compiling platforms v2.0.0
   Compiling maplit v1.0.2
   Compiling memmap2 v0.2.3
   Compiling names v0.12.0
   Compiling retain_mut v0.1.7
   Compiling textwrap v0.15.0
   Compiling strsim v0.10.0
   Compiling sc-consensus-slots v0.10.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.18#32a4fe01)
   Compiling quick-error v2.0.1
   Compiling safe-mix v1.0.1
   Compiling getrandom v0.2.5
   Compiling instant v0.1.12
   Compiling value-bag v1.0.0-alpha.8
   Compiling generic-array v0.14.5
   Compiling ahash v0.7.6
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling unicase v2.6.0
   Compiling cc v1.0.73
   Compiling indexmap v1.8.0
   Compiling num-traits v0.2.14
   Compiling miniz_oxide v0.4.4
   Compiling num-integer v0.1.44
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.8
   Compiling num-bigint v0.2.6
   Compiling num-rational v0.2.4
   Compiling rayon v1.5.1
   Compiling atomic v0.5.1
   Compiling num-rational v0.4.0
   Compiling tracing-core v0.1.23
   Compiling sharded-slab v0.1.4
   Compiling lock_api v0.4.6
   Compiling threadpool v1.8.1
   Compiling thread_local v1.1.4
   Compiling tinyvec v1.5.1
   Compiling itertools v0.10.3
   Compiling ed25519 v1.4.1
   Compiling owning_ref v0.4.1
   Compiling wyz v0.5.0
   Compiling regex-automata v0.1.10
   Compiling cranelift-codegen-meta v0.80.1
   Compiling block-padding v0.1.5
   Compiling blake2b_simd v0.5.11
   Compiling blake2s_simd v0.5.11
   Compiling trie-root v0.17.0
   Compiling wasmi-validation v0.4.1
   Compiling wasm-instrument v0.1.1
   Compiling heck v0.3.3
   Compiling parity-wasm v0.32.0
   Compiling http v0.2.6
   Compiling form_urlencoded v1.0.1
   Compiling pest v2.1.3
   Compiling concurrent-queue v1.2.2
   Compiling async-mutex v1.4.0
   Compiling async-lock v2.5.0
   Compiling lru-cache v0.1.2
   Compiling linked_hash_set v0.1.4
   Compiling dns-parser v0.8.0
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling clang-sys v1.3.1
   Compiling matrixmultiply v0.3.2
   Compiling bytes v0.4.12
   Compiling semver v0.6.0
   Compiling rand_core v0.6.3
   Compiling zstd-sys v1.6.2+zstd.1.5.1
   Compiling backtrace v0.3.64
   Compiling wasmtime-runtime v0.33.1
   Compiling psm v0.1.17
   Compiling secp256k1-sys v0.4.2
   Compiling ring v0.16.20
   Compiling libz-sys v1.1.5
   Compiling wepoll-ffi v0.1.2
   Compiling blake3 v0.3.8
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling tikv-jemalloc-sys v0.4.3+5.2.1-patched.2
   Compiling lz4-sys v1.9.3
   Compiling unicode-normalization v0.1.19
   Compiling matchers v0.0.1
   Compiling cranelift-codegen v0.80.1
   Compiling http-body v0.4.4
   Compiling semver-parser v0.10.2
   Compiling pest_meta v2.1.3
   Compiling build-helper v0.1.1
   Compiling rand_chacha v0.3.1
   Compiling quote v1.0.16
   Compiling aho-corasick v0.7.18
   Compiling bstr v0.2.17
   Compiling os_str_bytes v6.0.0
   Compiling nom v7.1.1
   Compiling fdlimit v0.2.1
   Compiling which v4.2.5
   Compiling winapi-util v0.1.5
   Compiling atty v0.2.14
   Compiling time v0.1.44
   Compiling dirs-sys-next v0.1.2
   Compiling region v2.2.0
   Compiling ansi_term v0.12.1
   Compiling socket2 v0.4.4
   Compiling miow v0.3.7
   Compiling socket2 v0.3.19
   Compiling hostname v0.3.1
   Compiling winreg v0.6.2
   Compiling if-addrs v0.6.7
   Compiling net2 v0.2.37
   Compiling schannel v0.1.19
   Compiling fs-swap v0.2.6
   Compiling fs2 v0.4.3
   Compiling dirs-sys v0.3.7
   Compiling remove_dir_all v0.5.3
   Compiling rpassword v5.0.1
   Compiling libloading v0.7.3
   Compiling generic-array v0.12.4
   Compiling futures-lite v1.12.0
   Compiling async-channel v1.6.1
   Compiling quicksink v0.1.2
   Compiling rand_core v0.5.1
The following warnings were emitted during compilation:

warning: "jemalloc support for `x86_64-pc-windows-msvc` is untested"

error: failed to run custom build command for `tikv-jemalloc-sys v0.4.3+5.2.1-patched.2`

Caused by:
  process didn't exit successfully: `F:\substrate-node-template\target\release\build\tikv-jemalloc-sys-4cd2c2a2ae709ff5\build-script-build` (exit code: 101)
  --- stdout
  TARGET=x86_64-pc-windows-msvc
  HOST=x86_64-pc-windows-msvc
  NUM_JOBS=4
  OUT_DIR="F:\\substrate-node-template\\target\\release\\build\\tikv-jemalloc-sys-ccc1933a0d80bca5\\out"
  BUILD_DIR="F:\\substrate-node-template\\target\\release\\build\\tikv-jemalloc-sys-ccc1933a0d80bca5\\out\\build"
  SRC_DIR="C:\\Users\\Xtrotrik\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\tikv-jemalloc-sys-0.4.3+5.2.1-patched.2"
  cargo:warning="jemalloc support for `x86_64-pc-windows-msvc` is untested"
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-pc-windows-msvc")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_x86_64-pc-windows-msvc = None
  CC_x86_64_pc_windows_msvc = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-msvc = None
  CFLAGS_x86_64_pc_windows_msvc = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("false")
  CC="C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe"
  CFLAGS="-nologo -MD -O2 -Brepro -W4"
  JEMALLOC_REPO_DIR="jemalloc"
  running: "sh" "F:/substrate-node-template/target/release/build/tikv-jemalloc-sys-ccc1933a0d80bca5/out/build/configure" "--disable-cxx" "--with-private-namespace=_rjem_" "--host=x86_64-pc-win32" "--build=x86_64-pc-win32" "--prefix=F:\\substrate-node-template\\target\\release\\build\\tikv-jemalloc-sys-ccc1933a0d80bca5\\out"

  --- stderr
  thread 'main' panicked at 'failed to execute command: program not found', C:\Users\Xtrotrik\.cargo\registry\src\github.com-1ecc6299db9ec823\tikv-jemalloc-sys-0.4.3+5.2.1-patched.2\build.rs:334:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by nakul1010** [comment]
I am facing the same issue.

**Comment by Xtrotrik** [comment]
> I think there's the problem with the current master version cloned a old master version it works. [Here's](https://github.com/substrate-developer-hub/substrate-node-template/releases/tag/polkadot-v0.9.17) the version that I cloned.

Thank you its working

**Comment by nakul1010** [comment]
Glad it work you can close the issue if no more doubts.

**Comment by NukeManDan** [comment]
jemalloc support for x86_64-pc-windows-msvc is untested" - do not use windows natively, use WSL2 for this to work. Can you confirm that this is on a windows machine and reproducible not working with the latest `main`? @Xtrotrik @nakul1010

**Comment by Liu-WeiHu** [comment]
> jemalloc support for x86_64-pc-windows-msvc is untested" - do not use windows natively, use WSL2 for this to work. Can you confirm that this is on a windows machine and reproducible not working with the latest `main`? @Xtrotrik @nakul1010
> 
> Jemalloc 对 x86 _ 64-pc-windows-msvc 的支持尚未经过测试”——不要本机使用 windows，使用 wsl2来实现这一点。您能否确认这是在 windows 机器上，并且不能与最新的主机一起工作？@ xtrotrik@nakul1010

I ran into this problem with ubuntu20.04 compilation as well

**Comment by Liu-WeiHu** [comment]
> > jemalloc support for x86_64-pc-windows-msvc is untested" - do not use windows natively, use WSL2 for this to work. Can you confirm that this is on a windows machine and reproducible not working with the latest `main`? @Xtrotrik @nakul1010
> > Jemalloc 对 x86 _ 64-pc-windows-msvc 的支持尚未经过测试”——不要本机使用 windows，使用 wsl2来实现这一点。您能否确认这是在 windows 机器上，并且不能与最新的主机一起工作？@ xtrotrik@nakul1010
> 
> I ran into this problem with ubuntu20.04 compilation as well

I switched to the polkadot-v0.9.17 tag and compiled properly

**Comment by Akbar30Bill** [comment]
Kind of same issue here on Fedora 34 after switching to polkadot-v0.9.17 solves the issue

**Comment by muddlebee** [comment]
Hi folks make sure you install libjemalloc-dev..

for ubuntu 
> 	sudo apt-get install libjemalloc-dev


and also make sure you have the build-essentials 
e.g. ubuntu

>sudo apt install build-essential

more info her https://docs.substrate.io/v3/getting-started/installation/

LFG!!

**Comment by Veniamin** [comment]
still doesn't work on wsl2 ubuntu 18
thread 'main' panicked at 'command did not execute successfully: "make" "install_lib_static" "install_include" "-j" "15"
  expected success, got: exit status: 2'
polkadot 0.9.18

**Comment by Mohit20Kumar** [comment]
> I think there's the problem with the current master version cloned a old master version it works. [Here's](https://github.com/substrate-developer-hub/substrate-node-template/releases/tag/polkadot-v0.9.17) the version that I cloned.

How did u do this???? How to clone a old version?
