### ISSUE TITLE
error: failed to start node

### ISSUE THREAD

**Issue by wp-coin** [substrate-developer-hub/substrate-node-template#419]
```
./target/release/node-template --dev
2023-03-19 00:06:37 Substrate Node
2023-03-19 00:06:37 ✌️  version 4.0.0-dev-d67d92de1be
2023-03-19 00:06:37 ❤️  by Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2023
2023-03-19 00:06:37 📋 Chain specification: Development
2023-03-19 00:06:37 🏷  Node name: acid-pipe-4494
2023-03-19 00:06:37 👤 Role: AUTHORITY
2023-03-19 00:06:37 💾 Database: RocksDb at /tmp/substrateKcLThW/chains/dev/db/full
2023-03-19 00:06:37 ⛓  Native runtime: node-template-100 (node-template-1.tx1.au1)
Error: Service(Client(VersionInvalid("cannot deserialize module: UnknownOpcode(192)")))
2023-03-19 00:06:37 Cannot create a runtime error=Other("cannot deserialize module: UnknownOpcode(192)")

```

why am I getting this error on windows 11 

also tried on  wsl2 ( ubuntu)

**Comment by al3mart** [comment]
This issue might be solved by https://github.com/paritytech/substrate/pull/13804 as pointed out [here](https://github.com/paritytech/subport/issues/32#issuecomment-1493893071).

**Comment by klaus993** [comment]
Hello! Why is this closed? This isn't fixed AFAIK

@bgodlin @wp-coin I believe this is a rust version problem. The documentation is outdated, as it indicates the output of `rustup show` (and I tried this combination with no success):

```
# rustup show

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.62.1 (e092d0b6b 2022-07-16)

# rustup +nightly show

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by +toolchain on the command line)
rustc 1.65.0-nightly (34a6cae28 2022-08-09)
```

Both versions are important (as substrate is compiled with stable version, but wasm is added with nightly) and I don't know if there is a particular combination of them that works, or if it's just the stable or just the nightly that produces this bug.
I tried so many combinations that I lost track, but I got it to work without this error by doing 2 things

First: I have this `rustup show` output:

```
# rustup show

active toolchain
----------------

nightly-2023-01-01-x86_64-unknown-linux-gnu (overridden by '/root/rust-toolchain.toml')
rustc 1.68.0-nightly (574b64a97 2022-12-31)

# rustup +nightly show

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by +toolchain on the command line)
rustc 1.70.0-nightly (4087deacc 2023-04-12)
```

Lastly, I added this file to the root of the substrate-node-template repo (as pointed out here https://stackoverflow.com/a/75956899):
`rust-toolchain.toml`:
```toml
[toolchain]
channel = "nightly-2023-01-01"
components = [ "rustfmt" ]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
```

Today I found out that the template in this repo is actually coming from here: https://github.com/paritytech/substrate/tree/master/bin/node-template, where the `rust-toolchain.toml` file actually exists, with similar contents. I would and will give this a try.

Documentation is highly confusing on linux installation, there isn't any rust version pinned to any release, so to make it work it's trial and error, and if you don't have a really powerful server, you will wait 20+ minutes for every test.

**Comment by klaus993** [comment]
Hello there!

Confirming that it works with latest rust versions:
(running on x86_64 Ubuntu 22.04)

```
# rustup show

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by '/home/ubuntu/substrate-node-template/rust-toolchain.toml')
rustc 1.71.0-nightly (5ea3f0ae0 2023-05-23)

# rustup +nightly show

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by +toolchain on the command line)
rustc 1.71.0-nightly (5ea3f0ae0 2023-05-23)
```

Procedure:

1. Do everything as-is until step 3 of [_Compile a Substrate node_](https://docs.substrate.io/install/linux/#compile-a-substrate-node).
2. Before running step 4 (`cargo build --release`) add [this file](https://github.com/paritytech/substrate/blob/2000147ad910f594a998fd6444f259a234013f27/bin/node-template/rust-toolchain.toml) to the root of the repo
3. Proceed to run the node:
```
./target/release/node-template --dev
```
