### ISSUE TITLE
cant compile anymore

### ISSUE THREAD

**Issue by 2075** [substrate-developer-hub/substrate-node-template#47]
since yesterday compiling the template on macos does not seem to compute anymore:

```
error[E0424]: expected value, found module `self`
   --> /Users/m/.cargo/git/checkouts/substrate-7e08433d4c370a21/45b9f0a/frame/support/src/traits.rs:913:11
    |
911 | / bitmask! {
912 | |     /// Reasons for moving funds out of an account.
913 | |     #[derive(Encode, Decode)]
    | |              ^^^^^^ `self` value is a keyword only available in methods with a `self` parameter
914 | |     pub mask WithdrawReasons: i8 where
...   |
929 | |     }
930 | | }
    | |_- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0424`.
error: could not compile `frame-support`.

To learn more, run the command again with --verbose.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

for some reason even going back to alpha 8 or 6 does not seem to make rustc happy anymore. 
already tried separate machines, fresh pull, cleaning cache etc.

any ideas?

**Comment by 2075** [comment]
the same result for the kitchen node, which is still on alpha.8

**Comment by JoshOrndorff** [comment]
One hypothesis is that something changed in the rust compiler itself. Did you update rust recently? Can you post the output of running `rustup show`?

**Comment by 2075** [comment]
rolling back to an older nightly solves the problem. this works over here:
```
rustc +nightly --version
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
```

**Comment by duval1024** [comment]
reinstall all toolchains can fix this problem.

**Comment by 2075** [comment]
thanks, @duval1024, the solution is already written above :)

actually a reinstall would be unlikely to fix, as a reinstall without a version would recreate the same environment with the latest nightly build.

manually going back to the above helps, it's not windows ;)
