### ISSUE TITLE
build-only-wasm script

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-node-template#5]
The main substrate node has [a script](https://github.com/paritytech/substrate/blob/734f1c3d066ba0c700d19aee5feb79869aae4228/scripts/build-only-wasm.sh) to build _just_ the runtime wasm. 

It is useful for doing runtime upgrades. It would be nice to have that script here too. One way to do that would be to add it to the `node-template` in the main Substrate repo.

**Comment by riusricardo** [comment]
I tried it when Basti mentioned it and  I agree that it's useful. 
I think that we are trying to get rid of scripts because they are not compatible with all platforms. 
We could add a description to the readme instead of importing it here.

**Comment by riusricardo** [comment]
@JoshOrndorff Do you still want to explore this idea? We need to confirm if it still works now that there are no more scripts on the main Substrate repo.

**Comment by JoshOrndorff** [comment]
I just looked over the script. It looks like the written instructions could be something like.

It is necessary to build the entire node on the first build, however you can build _only_ the wasm binary on subsequent builds by running.
```bash
 cargo run --release --manifest-path="target/release/wbuild-runner/node-template-runtime/Cargo.toml" \
    | grep -vE "cargo:rerun-if-|Executing build command"
```

The only bit I'm unsure about is the  `grep`. From the man-page I see
```
       -v, --invert-match
              Invert the sense of matching, to select non-matching lines.
```
but I don't have any docs about -E and I'm not sure why we'd want to filter the output.

**Comment by bkchr** [comment]
Why not use the script?

The grep just removes some output that is not needed for the user.

**Comment by JoshOrndorff** [comment]
> Why not use the script?

I'm fine with using the script. @shawntabrizi do you want to make the case for avoiding scripts?

**Comment by araa47** [comment]
@JoshOrndorff  this script will be useful for sure, especially since this repository is usually the starting point for many developers building their own parachains.

**Comment by JoshOrndorff** [comment]
You can build just the wasm runtime with the command `cargo build --release -p node-template-runtime`.

I'm not sure the script in the main substrate repo even works anymore and opened https://github.com/paritytech/substrate/issues/6852 to check on it.

**Comment by NukeManDan** [comment]
Checking in here guys - this issue is still open, should it be closed?

**Comment by jimmychu0807** [comment]
Reading the whole thread, I feel we can keep this simple and just have developers get the latest wasm runtime with `cargo build --release`.

If there is a strong case to just having wasm, but not the native runtime built, please reopen this and let me/us know.
