### ISSUE TITLE
Add toolchain file

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-node-template#56]
Users occasionally have issues building the template because of breaking changes in rustc. When we release node templates, we should include a toolchain file to make it clear what version of the compiler is known to work.

references:
https://github.com/rust-lang/rustup#the-toolchain-file
https://github.com/paritytech/polkadot/issues/1163

**Comment by s3krit** [comment]
@JoshOrndorff Every night, we rebuild our [main CI image](https://hub.docker.com/r/paritytech/ci-linux) and test it against building substrate. It would be possible to expand this job to then (on a successful build), update `.toolchain` accordingly and submit a PR against Substrate. Could be noisy until we nail auto-merging.

**Comment by JoshOrndorff** [comment]
@s3krit I would love to have a toolchain file in the main Substrate repo and it would help have a standard way to determine what toolchain to put in the template's own toolchain file.  If you think it's a good idea, I'm all for it.

**Comment by 2075** [comment]
hey there, any news on this? again we accidentially nuked our build machine with an upgrade, would be super duper helpful, if we had a pointer towards which versions to pin. :D

**Comment by JoshOrndorff** [comment]
I guess this is solved by #92 right?
