### ISSUE TITLE
This repo takes forever to clone

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-node-template#60]
When doing a fresh clone of this repo, the download takes a very long time. I believe this is because at one point there was a large binary file committed to the repo and it is still in the history.

We should solve this to lower friction for new template users.

**Comment by kaichaosun** [comment]
Node-template users should not care about git history when using it.

In most languages, there is a build-in command to create a new project from a template, like `sbt new hello-template` for Scala.
Rust doesn't provide this feature now, there is tracked [here](https://github.com/rust-lang/cargo/issues/5151).
But there exists a community project that can do a similar thing [here](https://github.com/ashleygwilliams/cargo-generate).  We can probably try this.

**Comment by wheresaddie** [comment]
so to implement this, would look something like this:

`cargo generate --git https://github.com/substrate-developer-hub/substrate-node-template`

**Comment by danforbes** [comment]
Additional documentation on this topic https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones

**Comment by JoshOrndorff** [comment]
Shallow clone is a little different. Users who use a shallow clone would not be able to push to their own repos under some circumstances https://stackoverflow.com/questions/6900103/why-cant-i-push-from-a-shallow-clone

It could be used as part of a workflow where the user just wants to get the code and then start their own repo from scratch, but then they wouldn't be able to pull in upstream node-template changes as we make them. Same with Kaichao's approach.

**Comment by wheresaddie** [comment]
@JoshOrndorff could you apply:

`git checkout -b feature-x
#some work and some commits happen
#some time passes
git fetch upstream
git rebase upstream/master`
