### ISSUE TITLE
upload contracts fail

### ISSUE THREAD

**Issue by ProgramAPE** [substrate-developer-hub/substrate-node-template#63]
I run my local private network.
When i use the builtin Alice and Bob to start the two nodes network. Upload the Contract wasm file is OK. The contract can be called normally. But when I use the <subkey --sr25519 generate > keys to boot a local two nodes network. when I am uploading the contract wasm file it failed. and say: invalid. why?  Did someone knows what happened?

**Comment by danforbes** [comment]
Are you using the node template with [the Contracts pallet](https://substrate.dev/rustdocs/v2.0.0-rc4/pallet_contracts/index.html)? If so, can you please provide screenshots or additional error details from your browser's console? If not, can you please clarify what it is that you're working on when you encounter this problem?

**Comment by ProgramAPE** [comment]
@danforbes Thanks for help me.  The problem was solved.
I set up the contract with this doc : https://substrate.dev/docs/en/tutorials/add-a-pallet-to-your-runtime/#install-the-node-template
and use the contract-pallet enabled node to build a two-node local network with doc:https://substrate.dev/docs/en/tutorials/start-a-private-network/. 
The problem comes when I generate the chain-spec.  I didn't generate the raw JSON file.  when I am generating the raw JSON file again and problem is gone.
I also wonder why there is only one Account's keys were added in the chain-spec file. The <local> chain-spec file has two accounts' keys. 
Do you know why? Thanks a lot.

**Comment by wheresaddie** [comment]
@ProgramAPE you might look at the [chain-spec](https://substrate.dev/rustdocs/v2.0.0-rc4/sc_service/struct.GenericChainSpec.html) implementation and documentation
