### ISSUE TITLE
Node Template not Compiling on Windows Following Official Tutorial

### ISSUE THREAD

**Issue by gollum18** [substrate-developer-hub/substrate-node-template#64]
Hi, a friend of mine attempted to setup and build the substrate node template on Windows 10 following the official [tutorial](https://substrate.dev/docs/en/knowledgebase/getting-started/windows-users) in preparation for the Hackusama hackathon.

He ended up getting this error during the process

> error: failed to run custom build command for node-template-runtime v2.0.0-rc4 (C:\Users\jdurr\AppData\Roaming\SPB_16.6\substrate-node-template\runtime)
> 
> Caused by:
>   process didn't exit successfully: C:\Users\jdurr\AppData\Roaming\SPB_16.6\substrate-node-template\target\release\build\node-template-runtime-d6e898ad2ca934e3\build-script-build (exit code: 1)
> --- stderr
>    Compiling winapi v0.3.9
> error: failed to write C:\Users\jdurr\AppData\Roaming\SPB_16.6\substrate-node-template\target\release\wbuild-runner\node-template-runtime3267355145636852925\target\x86_64-pc-windows-msvc\release\.fingerprint\winapi-2db33ecc220f2cd2\run-build-script-build_script_build-2db33ecc220f2cd2
> 
> Caused by:
>   The system cannot find the path specified. (os error 3)
> 
> warning: build failed, waiting for other jobs to finish...
> error: build failed

We know what the error implies that there is an issue with his build environment but were unable to figure out how to fix it. Has anyone else run into this issue before and if so, how did you fix it?

**Comment by danforbes** [comment]
@swader are you able to offer any assistance here? Unfortunately I do not have access to a Windows machine so it's difficult for me to provide much support :persevere:

**Comment by stiiifff** [comment]
You probably reached the infamous max path limit in Windows which is 260 chars (the path mentioned has 261). Try shortening it e.g. C:\Dev\substrate-node-template.

**Comment by Swader** [comment]
This is correct, shorten the path or [get rid of the limit](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/)

**Comment by danforbes** [comment]
Thank you very much, @stiiifff & @Swader :pray:
