### ISSUE TITLE
mv: cannot move 'substrate-node-template' to a subdirectory of itself, 'substrate-node-template/substrate-node-template'

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-node-template#7]
either the flaw is in the tutorial or in the script.

On this page https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain
When doing this:
```
substrate-node-new substrate-node-template <author-name>
substrate-ui-new substrate
```

I see this error:

```
substrate-node-new substrate-node-template myname

  Substrate Node Template Setup 
  Downloading project...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 71537  100 71537    0     0   236k      0 --:--:-- --:--:-- --:--:--  236k
mv: cannot move 'substrate-node-template' to a subdirectory of itself, 'substrate-node-template/substrate-node-template'
Customizing project...
Initializing repository...
Initializing WebAssembly build environment...
```

versions:
```
substrate --version; subkey --version
substrate 2.0.0-dc16bac5e-x86_64-linux-gnu
subkey 2.0.0
```
Please also add a --version to the scripts; but with the hash you can probably identify which version I have, no?
```
substrate-node-new --version
  Substrate Node Template Setup 
  Usage: substrate-node-new <NAME> <AUTHOR>

sha256sum substrate-node-new
3d92bcbbd5f2e3d8517de121a2c4babec1b68232138187d38e11fd039b7b8fa2  substrate-node-new
```

**Comment by riusricardo** [comment]
Thanks for reporting this issue. We are currently working on migrating all the Dev Hub to Substrate v2.0. Most of this scripts will be deprecated.
Creating your first chain tutorial will be simplified and updated to work without this scripts.

**Comment by drandreaskrueger** [comment]
What is the consequence of that error?

Because at first sight it seems to still work.

**Comment by riusricardo** [comment]
It could be an error related to the directory from where it is being executed.
Closing because it will be deprecated soon.
