### ISSUE TITLE
PoE tutorial should support parachain template?

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-node-template#71]
This issue is to consider and possibly implement changes to the PoE tutorial so that it can be applied to the parachain template as well as the node template. Because the two templates are structured so similarly, I suspect it will take very little wording changes and little confusion. Of course if this is not the case, we don't need to do it.

**Comment by wheresaddie** [comment]
yes- in addition the PoE is also referred to as dapp in the primary index of tutorials and I would suggest we define a naming structure to not create additional confusing to newcomers.

**Comment by danforbes** [comment]
@JoshOrndorff - why are you suggesting this change?

**Comment by JoshOrndorff** [comment]
The narrative that we are pushing is that developing a Substrate runtime looks (nearly*) the same whether you're building a standalone chain or a cumulus parachain. Further we are hypothesizing that many people will want to build cumulus parachains. The PoE tutorial is the most basic introduction to runtime development, so it would be nice if it worked in either of those two (nearly*) identical contexts.

**Comment by jimmychu0807** [comment]
Another alternative maybe add that section in the cumulus workshop / parachain tutorial (if we have one), and linking to there at the end of the PoE tutorial? So PoE tutorial can stay simple.

I don't have too strong a stance whether to append the content to the PoE tutorial or in cumulus workshop yet, but feel it maybe better adding on the cumulus workshop side.

**Comment by wheresaddie** [comment]
if cumulus is going to be a major theme in substrate dev it makes sense to produce a tutorial centeric to people wanting to focus on utilizing it

**Comment by jimmychu0807** [comment]
Closing this here, as it is moved to https://github.com/substrate-developer-hub/substrate-parachain-template/issues/22
