### ISSUE TITLE
All template forks start with failing CI job

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-node-template#74]
The node template is meant to be forked and turned into application specific blockchains.

Because this repo has a ci job that publishes a docker image (for the Substrate playground to use) so does every fork of this repo. None of the forks have the credentials to push the docker image, so the ci fails. The result is that every newly-forked node-template has a red :x: .

**Comment by danforbes** [comment]
Good looking out...I had noticed this too. Do you have any thoughts on how to address this?

**Comment by JoshOrndorff** [comment]
Not specifics. My only thought is that the CI would have to run on another repo (maybe the palyground?) to totally solve it. We could alleviate the pain by changing that CI to only run when we create new tags instead of on each merge to master, and it might make sense to do that anyway, but it wouldn't fundamentally solve _this_ issue.

**Comment by wheresaddie** [comment]
yeah might be worth pinging @jeluard and see if we can integrate the run of CI into the IDE

**Comment by jeluard** [comment]
Interesting side effect! GitHub actions are such a nice tool to shoot yourself in the foot 😭 
Short term we can add a [conditional](https://github.community/t/stop-github-actions-running-on-a-fork/17965/2) to make sure it only runs for the right repo. I might have to add to safe guards to playground before .. 😄

**Comment by wheresaddie** [comment]
yes, makes totally sense.. it's always good to have a safety :)

**Comment by danforbes** [comment]
Julien addressed this Issue in https://github.com/substrate-developer-hub/substrate-node-template/commit/912fa0f7214f19796d59ebc15bf949bc4909a1ea.
