### ISSUE TITLE
Renameing the template results in an error

### ISSUE THREAD

**Issue by rwindegger** [substrate-developer-hub/substrate-node-template#78]
I'm renameing the template using search and replace. After renaming extrinsics are not working anymore. The following error occures:
```WARN sc_rpc::author  Failed to submit extrinsic: Extrinsic verification error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature```
What did I do wrong?

**Comment by wheresaddie** [comment]
can you post some of your code or the complete error log @rwindegger

**Comment by rwindegger** [comment]
To reproduce the issue just search and replace "template" with a new name. There are around 80 occurrences in 22 files. The build is working fine but at runtime when calling an extrinsic the warning is issued and the extrinsic is not executed.

**Comment by rwindegger** [comment]
Just to make reproducing easier I've added a fork and renamed it to node-demo: https://github.com/rwindegger/substrate-node-demo

**Comment by JoshOrndorff** [comment]
> just search and replace "template" with a new name

Like using a sledge hammer to tap in photo-hanging nails. A better starting point would be to search for `node-template` and replace with `rwindegger-chain`, then search for `node_template` and replace with `rwindegger_chain`.

But really there are multiple crates and string to update in their own appropriate ways. I recommend starting with the search and replace I mentioned above, then share the repo if it doesn't build. I'll be able to help you from there.

**Comment by rwindegger** [comment]
@JoshOrndorff I've reverted the changes and tested if extrinsics are working. Then I followed your advice. The build is working fine but as soon as I try extrinsics the same error happens. You can find the reproduction repository at https://github.com/rwindegger/substrate-node-demo

![image](https://user-images.githubusercontent.com/12802869/91734284-10157c80-ebab-11ea-8e0f-14495096e398.png)

**Comment by JoshOrndorff** [comment]
I'm glad it is building. The problem now is because the UI needs to know the types your node uses. When you use the node template, the UI detects it, and uses the appropriate types for you. Sine you have renamed your template, the UI cannot tell that it is still basically the node template, so you need to add your own custom types. In the Apps UI, go the the developer settings, and enter:

```json
{
  "Address": "AccountId",
  "LookupSource": "AccountId"
}
```

**Comment by rwindegger** [comment]
Thanks that was the missing information.

**Comment by danforbes** [comment]
FYI I created a script that can help rename the pallet template and stuff. I have not tested it with the latest release, but PRs are always welcome :wink: https://github.com/danforbes/substrate-devhub-utils

**Comment by WB-Expert5007** [comment]
Hi, Everyone.
I hope you and your family are in good health.
Please help me.

I am going to delete all accounts of substrate node template like "Bob", "Charlie", "Dave" etc and also to rename the "alliece" as "Alex".
How can I do this?
