### ISSUE TITLE
sccache: error: Server startup failed: Address already in use (os error 98)

### ISSUE THREAD

**Issue by NachoPal** [substrate-developer-hub/substrate-node-template#79]
Hi, I just cloned the repository, and from master branch, when I try to run the docker container I get:

```
$ ./scripts/docker_run.sh
*** Start Substrate node template ***
Removing network aquila-validator-node_default
Creating network "aquila-validator-node_default" with the default driver
   Compiling autocfg v1.0.0
   Compiling lazy_static v1.4.0
   Compiling smallvec v1.4.1
   Compiling typenum v1.12.0
   Compiling getrandom v0.1.14
   Compiling memchr v2.3.3
sccache: error: Server startup failed: Address already in use (os error 98)
sccache: error: Server startup failed: Address already in use (os error 98)
error: could not compile `smallvec`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
sccache: error: Server startup failed: Address already in use (os error 98)
sccache: error: Server startup failed: Address already in use (os error 98)
sccache: error: Server startup failed: Address already in use (os error 98)
error: build failed
```

**Comment by JoshOrndorff** [comment]
Hi @NachoPal thanks for using the template!

This seems like an issue with sccache, more than an error with the node template. Are you able to build the template when you don't use `sccache`?

**Comment by NachoPal** [comment]
@JoshOrndorff is it possible to compile the node without `sccache`? Isn't it part of the docker image?

**Comment by JoshOrndorff** [comment]
Ahh, I see. You're using the docker image that's included in this repo. I didn't realize that.

It is possible to compile locally by setting up a [substrate developer environment](https://substrate.dev/docs/en/knowledgebase/getting-started/) and running `cargo build --release`.

That being said, we do want the docker image to work as well, so this is a valid bug report. I'm assigning @kaichaosun who worked on that docker image.

**Comment by JoshOrndorff** [comment]
Actually, we should have CI that tests this.

**Comment by JoshOrndorff** [comment]
Okay, so I ran the same `./scripts/docker_run.sh` command shown in the original post locally, and it worked as expected. @NachoPal I don't know what ports sccache wants to use, but is it possible you have another process using them? What if you restart your computer?

**Comment by NachoPal** [comment]
I looked for that and I didn't find it. I'll try to restart the computer.

**Comment by NachoPal** [comment]
Still the same

**Comment by NachoPal** [comment]
https://github.com/mozilla/sccache/issues/824

**Comment by kaichaosun** [comment]
@NachoPal the script works for me. I'm wondering how you met this issue with your hardware.

**Comment by wheresaddie** [comment]
@NachoPal I ran this and it worked for me as well, I assume it is working for you also, if this isn't the case please re-open the issue and let us know. thanks!
