### ISSUE TITLE
node 12

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-node-template#8]
Suggestion for https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain
```
sudo npm cache clean -f
sudo npm install -g n
sudo n v11.15.0
sudo npm install -g npm
node --version; npm --version
```
> v11.15.0
> 6.13.0

had also tried

    sudo n stable
    node --version

> v12.13.0

but that resulted in 

    substrate-ui-new substrate

failing to build, because blake2js ELIFECYCLE.

With node v11.15.0 it runs through just fine. It's from April 2019.

**Comment by riusricardo** [comment]
Closing because it will be deprecated soon.
