### ISSUE TITLE
Transactions in orphaned blocks are not being replayed after re-org

### ISSUE THREAD

**Issue by gnome32** [substrate-developer-hub/substrate-node-template#82]
The below testing was performed with utxo-workshop (a PoW chain), however, Joshy has also confirmed similar behaviour in the node template (Aura).

I wanted to test that transactions in orphaned blocks will indeed be replayed after re-orgs. Under re-org conditions, the assumed behaviour was that nodes will notice and repopulate the transaction mempool with any transactions that were previously in the shorter chain, but missing in the new longer (re-orged) chain. It would then re-broadcast them on the new fork.

Testing as follows (utxo-workshop, PoW) -

- Launch 2 x nodes, they're in PoW consensus
- Disconnecting/isolating them (docker network disconnect bridge xxxx)
- wait for one of the nodes to have a significantly smaller chain and executing the utxo extrinsic spend on it only (tx 0xdbc75ab8ee9b83dcbcea4695f9c42754d94e92c3c397d63b1bc627c2a2ef94e6 as per https://github.com/substrate-developer-hub/utxo-workshop )
- reconnect the 2 nodes, triggering the reorg to longer chain (which does not above tx)
- the tx does not appear to be re-broadcasted and it never hits the new longer chain

Joshy has also tested this with 2 x node-template nodes by intermittently terminating each node, allowing one to extend further, bringing them both back online, allowing them to come to consensus on the longer chain - https://www.twitch.tv/videos/736038706 . I don't have a lot of experience with Aura, however, it appears the behaviour may be similar.

Perhaps I have misunderstood something or am doing something wrong. Regardless, transaction replay should work under the simple conditions I have described. This behaviour is important for any type of blockchain, regardless of consensus rules. Indeed, this is how Bitcoin behaves. Bitcoin will retain transactions for a period of time after many block confirmations on the off chance of a long re-org. This is important for PoW chains as there is no concept of a hard 'finality', with confidence rather being found due to probability as the chain is extended. Retaining and replaying transactions is particularly important for minority hash chains such as ETC (although bigger fundamental problems still apply ;) ).

I cannot comment too much on PoA, however, even PoA may break down under super-majority dishonest authority behaviour. In some scenarios re-orgs might be expected. Users should not have resubmit extrinsics. Nodes in the wild don't always play nice.

**Environment**
Ubuntu 20, utxo-workshop RC6, rustc 1.45.2

**Comment by gnome32** [comment]
The above behaviour also applies to account-based extrinsics on utxo-workshop.

**Comment by JoshOrndorff** [comment]
cc @bkchr @tomusdrw @nikvolf This is the issue I was asking about in Element chat today.

**Comment by tomusdrw** [comment]
After taking a look at Joshy's logs it seems like a bug to me. The log line that resubmits transactions is never triggered:
https://github.com/paritytech/substrate/blob/da260bddd8ace6339eeb675a91eec496002ead33/client/transaction-pool/src/lib.rs#L646

It seems to be either because we don't have `tree_route` or `resubmit==false`, but it seems unlikely, or due to `pruned_log` or some other notification being missed.
It seems that `pruned_log` prevents a situation where we re-import transaction that is part of the enacted chain, but maybe there is some issue there:
https://github.com/paritytech/substrate/blob/da260bddd8ace6339eeb675a91eec496002ead33/client/transaction-pool/src/lib.rs#L638

@NikVolf wdyt?

**Comment by JoshOrndorff** [comment]
Here's the Polkadot JS docs about mortal transactions https://github.com/polkadot-js/api/blob/master/docs/start/api.tx.md#under-the-hood

**Comment by gnome32** [comment]
> Here's the Polkadot JS docs about mortal transactions https://github.com/polkadot-js/api/blob/master/docs/start/api.tx.md#under-the-hood

Thanks Joshy. Is mortality mutable after a transaction is signed? Or is mortality part of the transaction and therefore locked-in when the transaction is signed? Am curious to know how this applies to unsigned extrinsics (ie in utxo-workshop).

**Comment by wheresaddie** [comment]
Creating a mortal transaction means you state that your transaction is only valid between a certain amount of blocks. By signing that message when someone tries to replay it, the transaction will fail @gnome32 

for utxo-- `TaggedTransactionQueue` API handles all incoming extrinsics, not just UTXO transactions. This gives a runtime a control of the extrinsic validation process...  Upon its completion, `validate_transaction` function yields the `TransactionValidity` structure that contains hints for the transaction pool to order and prioritize the extrinsic.. Im unaware of if you can apply muting to UTXO.. let me ping @jimmychu0807

**Comment by gnome32** [comment]
https://github.com/wheresaddie thank you for the explanation. FYI I do not want to create mortal utxos. I was only asking to determine if mortality was the cause of utxos not being replayed (after re-orgs).

I expect utxos to always be replayable.

**Comment by gnome32** [comment]
> After taking a look at Joshy's logs it seems like a bug to me. The log line that resubmits transactions is never triggered:
> https://github.com/paritytech/substrate/blob/da260bddd8ace6339eeb675a91eec496002ead33/client/transaction-pool/src/lib.rs#L646
> 
> It seems to be either because we don't have `tree_route` or `resubmit==false`, but it seems unlikely, or due to `pruned_log` or some other notification being missed.
> It seems that `pruned_log` prevents a situation where we re-import transaction that is part of the enacted chain, but maybe there is some issue there:
> https://github.com/paritytech/substrate/blob/da260bddd8ace6339eeb675a91eec496002ead33/client/transaction-pool/src/lib.rs#L638
> 
> @NikVolf wdyt?

My testing has shown that line 617 always holds false and therefore skips the entire if block during reorg events -

https://github.com/paritytech/substrate/blob/da260bddd8ace6339eeb675a91eec496002ead33/client/transaction-pool/src/lib.rs#L617

I see the txpool trace log ("Pruning transactions") from line 611 ok.. but it will then skip and continue on to line 676 onwards.

FYI Joshy's logs (with ltxpool trace) at - https://gist.githubusercontent.com/JoshOrndorff/9ea7d8734ae570be8303bb11a9913315/raw/dd5e80ed67d3617324d3a51573229c058f107f33/Alice.log

Do I have this issue in the right repository? Seems like a wider problem and fairly important for reorg behavior.

@tomusdrw @NikVolf @JoshOrndorff

**Comment by bkchr** [comment]
> My testing has shown that line 617 always holds false and therefore skips the entire if block during reorg events -

I assume you mean that the `tree_route` is always `None`?

**Comment by gnome32** [comment]
> > My testing has shown that line 617 always holds false and therefore skips the entire if block during reorg events -
> 
> I assume you mean that the `tree_route` is always `None`?

Yes tree_route is always None. Both before and after reorg. I've only just started digging in the transaction pool and still trying to understand the revalidation and treeroute logic. I don't have anything more atm.

**Comment by bkchr** [comment]
If the `tree_route` is never `Some(_)`, it can not work.

So the node with the smaller chain includes the transaction and after this node reorg to the longer chain, the transaction is not resubmitted? And the node with the smaller chain also prints that it is doing a reorg?

**Comment by gnome32** [comment]
> If the `tree_route` is never `Some(_)`, it can not work.
> 
> So the node with the smaller chain includes the transaction and after this node reorg to the longer chain, the transaction is not resubmitted? And the node with the smaller chain also prints that it is doing a reorg?

Yes exactly as you describe -

- I isolate two nodes, wait a while
- Node #1 has smaller chain (I submit tx and wait for confirmation)
- Node #2 has longer chain (has no txs)
- I connect the two nodes
- Node #1 reorgs to longer chain (and prints to console that it reorged)
- Node #1 never resubmits tx (I waited)

**Comment by bkchr** [comment]
@gnome32 https://github.com/paritytech/substrate/pull/7118 this will fix your problem. You can backport the patch to test it. Now you will see that the transaction is re-submitted, but rejected because the siganture is not valid. This invalid signature should be solved by using an immortal transaction.

**Comment by gnome32** [comment]
@bkchr great thank you, all working!
