### ISSUE TITLE
Allow bootnodes to connect without specifying peer-id?

### ISSUE THREAD

**Issue by gnome32** [substrate-developer-hub/substrate-node-template#83]
I note the following under a 2018 PR -

Allow bootnodes as IP:PORT, query Peer-id
https://github.com/paritytech/substrate/pull/386

The PR suggests that Substrate should be able to connect to nodes without specifying peer-id (ie --bootnodes /ip4/127.0.0.1/tcp/30333/p2p), with the peer-id being requested during initial connection. Am I misunderstanding something here? As of today, Substrate still appears to require multiaddr specifying peer-id -

... --bootnodes /ip4/127.0.0.1/tcp/30333/p2p
error: Invalid value for '--bootnodes <ADDR>...': invalid protocol string

There are no certificate authorities tying IP addresses to cryptographic identities etc.. so, just trying to understand the rationale here? This should not apply to PoW chains for example.

**Comment by wheresaddie** [comment]
[#6337](https://github.com/paritytech/substrate/issues/6337)

**Comment by gnome32** [comment]
> [#6337](https://github.com/paritytech/substrate/issues/6337)

Sorry I don't follow

**Comment by danforbes** [comment]
@bkchr can you please comment on the rationale behind this feature? You can control this capability with the `--no-mdns` flag.

        --no-mdns                  
            Disable mDNS discovery.
            
            By default, the network will use mDNS to discover other nodes on the local network. This disables it.

**Comment by danforbes** [comment]
cc @gnunicorn the author of the original PR mentioned in this Issue.

**Comment by jimmychu0807** [comment]
@gnome32 yes, to my understanding, we still need to provide the peer id in addition of the IP and port.

Since this is not a specific issue of node-template, I am closing this for now.
