### ISSUE TITLE
docker-compose has "exec format error"

### ISSUE THREAD

**Issue by wan9wu** [substrate-developer-hub/substrate-node-template#84]
$ ./scripts/docker_run.sh
*** Start Substrate node template ***
Removing substrate-node-template_dev_run_6519c3d98f54 ... done
Removing node-template                                ... done
Removing substrate-node-template_dev_run_6e5476f0e5e3 ... done
Removing substrate-node-template_dev_run_a6ac63c25e50 ... done
Removing network substrate-node-template_default
Creating network "substrate-node-template_default" with the default driver
Creating substrate-node-template_dev_run ... done
standard_init_linux.go:211: exec user process caused "exec format error"

how can i solve this problem?

**Comment by wheresaddie** [comment]
What is the architecture of the machine you are trying to execute the docker image on @wan9wu ?

**Comment by danforbes** [comment]
I just tried using this script for the first time and was able to get it working but I had to create a folder named `.local` first. Can you try that and see if it solves your problem?

**Comment by danforbes** [comment]
I'm going to close this issue due to lack of activity. @wan9wu please reopen this Issue or create a new one if you're still having problems.
