### ISSUE TITLE
failed to run custom build command for `node-template-runtime v2.0.0-rc6

### ISSUE THREAD

**Issue by luobin544** [substrate-developer-hub/substrate-node-template#85]
**Failed to execute command： cargo build --release**

_➜  substrate-node-template git:(fcd577e) cargo build --release
   Compiling node-template-runtime v2.0.0-rc6 (/Users/luobin/project/substrate-node-template/runtime)
   Compiling bindgen v0.53.3
   Compiling parity-scale-codec v1.3.4
   Compiling snow v0.7.1
   Compiling web-sys v0.3.42
   Compiling cranelift-codegen v0.66.0
   Compiling wasm-bindgen-futures v0.4.15
   Compiling frame-support-procedural v2.0.0-rc6 (https://github.com/paritytech/substrate.git?tag=v2.0.0-rc6#be8bb186)
   Compiling tiny-bip39 v0.7.3
   Compiling jsonrpc-client-transports v14.2.0
   Compiling linregress v0.1.7
   Compiling jsonrpc-server-utils v14.2.0
   Compiling hyper v0.12.35
   Compiling hyper-rustls v0.21.0
error: failed to run custom build command for `node-template-runtime v2.0.0-rc6 (/Users/luobin/project/substrate-node-template/runtime)`

Caused by:
  process didn't exit successfully: `~/project/substrate-node-template/target/release/build/node-template-runtime-833ee7d7fff70513/build-script-build` (exit code: 1)
  --- stderr
     Compiling wasm-build-runner-impl v1.0.0 (/~/project/substrate-node-template/target/release/wbuild-runner/node-template-runtime374117483696389994)
      Finished release [optimized] target(s) in 1.35s
       Running `~/project/substrate-node-template/target/release/wbuild-runner/node-template-runtime374117483696389994/target/x86_64-apple-darwin/release/wasm-build-runner-impl`
  Rust WASM toolchain not installed, please install it!
warning: build failed, waiting for other jobs to finish...
error: build failed

Clone the Node Template (version v2.0.0-rc6+1)
_

**Comment by wheresaddie** [comment]
Hi @luobin544 - please install [WASM toolchain ](https://substrate.dev/docs/en/knowledgebase/getting-started/#webassembly-compilation) and run the node build again and report with any further issues/logs. thanks!

**Comment by luobin544** [comment]
> WASM toolchain
> rustup update nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
 nightly-x86_64-apple-darwin unchanged - rustc 1.48.0-nightly (1fd5b9d51 2020-09-20)

>rustup target add wasm32-unknown-unknown --toolchain nightly
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date


But the execution of the command still fails： cargo build --release

**Comment by sapurai** [comment]
Experiencing the same issue.
Already reinstalled and updated everything several time.

`rustc --version`
rustc 1.48.0-nightly (1fd5b9d51 2020-09-20)

`cargo build --release`
error: failed to run custom build command for `node-template-runtime v2.0.0-rc6 (/Users/asavic/substrate-node-template/runtime)`

Caused by:
  process didn't exit successfully: `/Users/USER/substrate-node-template/target/release/build/node-template-runtime-2d8c1667f205182e/build-script-build` (exit code: 1)
  --- stderr
     Compiling wasm-build-runner-impl v1.0.0 (/Users/USER/substrate-node-template/target/release/wbuild-runner/node-template-runtime1510794836428480857)
      Finished release [optimized] target(s) in 0.38s
       Running `/Users/USER/substrate-node-template/target/release/wbuild-runner/node-template-runtime1510794836428480857/target/x86_64-apple-darwin/release/wasm-build-runner-impl`
  Rust WASM toolchain not installed, please install it!
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by danforbes** [comment]
This is a downstream bug in the Rust compiler that affects Mac users https://github.com/paritytech/subport/issues/32 This should be a reasonable workaround; first:

```shell
rustup toolchain install nightly-2020-08-23
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-08-23
```

Then when you build you specify the nightly to use:

```shell
cargo +nightly-2020-08-23 build
```

**Comment by luobin544** [comment]
> This is a downstream bug in the Rust compiler that affects Mac users [paritytech/subport#32](https://github.com/paritytech/subport/issues/32) This should be a reasonable workaround; first:
> 
> ```shell
> rustup toolchain install nightly-2020-08-23
> rustup target add wasm32-unknown-unknown --toolchain nightly-2020-08-23
> ```
> 
> Then when you build you specify the nightly to use:
> 
> ```shell
> cargo +nightly-2020-08-23 build
> ```

good job

**Comment by anhcao142** [comment]
I get this same error when trying to build with docker.

**Comment by danforbes** [comment]
@anhcao142 have you tried the workaround described above?

**Comment by anhcao142** [comment]
It's work but only with building from source. The docker version is not working, I think maybe it's because the rustup toolchain version in the docker image is outdated.

**Comment by danforbes** [comment]
Ahhhh that makes sense! Thank you for reporting :pray:
