### ISSUE TITLE
zsh: no such file or directory: ./target/release/node-template

### ISSUE THREAD

**Issue by sapurai** [substrate-developer-hub/substrate-node-template#87]
**Question**

I am trying to follow the [Create Your First Substrate Chain Tutorial](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/). I have successfully done all the steps with a small workaround for macOS suggested at Issue #85. Unfortunately the suggested workaround didn't work for nightly-2020-08-23 so I instead used nightly-2020-05-15. 

After the compilation was successful without any errors, I tried to run a temporary dev node with the command:
`./target/release/node-template --dev --tmp`

I executed the command within the substrate-node-template folder and it seems like node-template is missing in the release directory getting the following error:
`zsh: no such file or directory: ./target/release/node-template`

Would be great if someone could help me out with this issue.
Thanks!

**Comment by danforbes** [comment]
It sounds like your build still was not successful; the fact that `./target/release/node-template` doesn't exist is a pretty good sign that is the case. The only other thing I would suggest checking is `./target/debug/node-template` in the case that when you built it with the new nightly you forgot to specify the `--release` flag.

**Comment by wheresaddie** [comment]
following up to see if you were successful @sapurai

**Comment by sapurai** [comment]
Yes @wheresaddie it was the problem @danforbes described.
Solved by using the following command:
`cargo +nightly-2020-05-15 build --release`

Thank you very much!

**Comment by paulgarvey** [comment]
Hello, 

I am having the same issue but when I put in commend "cargo +nightly-2020-05-15 build --release" I get an error message saying:

"error: toolchain 'nightly-2020-05-15-x86_64-apple-darwin' is not installed" 

I am not sure what to do here, very new to this and would greatly appreciate any help!

**Comment by NukeManDan** [comment]
@paulgarvey - please see the https://substrate.dev/docs/en/knowledgebase/getting-started/ docs and use **substrate v3** - nightly builds are not required for substrate anymore (at least until rust breaks things upstream again 😝 )

**Comment by paulgarvey** [comment]
Thank you @Cryptorado

I did the steps as directed but for some reason I am gettin the message below:

"zsh: no such file or directory: ./target/release/node-template"

**Comment by Nimrah012** [comment]
I run the command ./target/release/node-template --dev --tmp it takes 7,8 hours but still not finished 
what should I do?
