### ISSUE TITLE
Compile runtime hanges over ten mins 

### ISSUE THREAD

**Issue by AsceticBear** [substrate-developer-hub/substrate-node-template#89]
**Question**

When compiling node-template, The compiler stuck here for over 10 minutes without any output.

```sh
   Checking kvdb-rocksdb v0.9.0
    Checking sc-client-db v0.8.0-rc6 (https://github.com/paritytech/substrate.git?tag=v2.0.0-rc6#be8bb186)
    Checking sc-service v0.8.0-rc6 (https://github.com/paritytech/substrate.git?tag=v2.0.0-rc6#be8bb186)
    Checking sc-cli v0.8.0-rc6 (https://github.com/paritytech/substrate.git?tag=v2.0.0-rc6#be8bb186)
    Building [=====================================================> ] 853/857: node-template-runtime(build)     
```

I have no idea how to deal with this situation, just wait ? or something else I can do. My local rust env is `rustc 1.48.0-nightly (7f7a1cbfd 2020-09-27)`.

**Comment by danforbes** [comment]
Hi, I have encountered this problem as well. Question: are you trying to build a "fresh" node template or is this something you've been hacking on for a while? I think I encounter this problem only in the latter circumstance. Can you try running `cargo clean` and rebuilding? Unfortunately it means you will have to start the build the scratch, but this is the kind of thing that has helped me in the past.

**Comment by AsceticBear** [comment]
1. It seems less likely to occurs if build from a fresh node template.  
2. The project I am working on is relatively large, the process I experience was that building until runtime crate, hangs for some time, then I ctrl+c to abort the compiling process. Finally, `cargo clean` and rebuild, it might be ok. Too much time wasted ... you must know.

**Comment by danforbes** [comment]
@gnunicorn, @bkchr - is this a situation that either of you is familiar with?

**Comment by gnunicorn** [comment]
>  It seems less likely to occurs if build from a fresh node template.

On what type of machine are you building? How long does the build take until that point?

Rust isn't particular quick with the compiling at the moment and opaque to the person in front, at this step we are actually building the project twice: once natively and once in wasm. So at some step in between it appears as if nothing happens and that can take up to half the total build time – if the other part took e.g. 10minutes then this process might take another 10min without any indicator of process (other than the CPU pumping hard).

**Comment by danforbes** [comment]
@AsceticBear - can you please let us know if you have any follow-up questions? If not, please close this Issue :pray:

**Comment by AsceticBear** [comment]
Sorry for the late reply. 

Machine type: 8  Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz Ubuntu 20.04 
Rustc version: rustc 1.48.0-nightly (7f7a1cbfd 2020-09-27)

It takes 20 minutes to finish `cargo check` the raw `substrate-node-template` on this machine. Thank you all for your reply, I close this issue.
