### ISSUE TITLE
no node_runtime.compact.wasm but substrate_node_template_runtime_wasm.compact.wasm

### ISSUE THREAD

**Issue by drandreaskrueger** [substrate-developer-hub/substrate-node-template#9]
In this tutorial https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain

it says

> If this completes successfully, it will update the file: ./runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm. You can go back to the Substrate UI, and in the Runtime Upgrade section, you can select this file and press upgrade.

but the filename after `scripts/build.sh` is slightly different; I suppose these are the files

```
ls  runtime/wasm/target/wasm32-unknown-unknown/release/*.wasm

runtime/wasm/target/wasm32-unknown-unknown/release/substrate_node_template_runtime_wasm.compact.wasm  runtime/wasm/target/wasm32-unknown-unknown/release/substrate_node_template_runtime_wasm.wasm
```
?

**Comment by drandreaskrueger** [comment]
I used https://github.com/substrate-developer-hub/substrate-package/blob/gav-demo/substrate-node-template/runtime/src/lib.rs and https://github.com/substrate-developer-hub/substrate-package/blob/gav-demo/substrate-node-template/runtime/src/demo.rs

**Comment by riusricardo** [comment]
Thanks for reporting it.
You are right, the files that you mention should work.
```
substrate_node_template_runtime_wasm.compact.wasm  

substrate_node_template_runtime_wasm.wasm
```
