### ISSUE TITLE
first time install failed, error[E0282]: type annotations needed

### ISSUE THREAD

**Issue by Maar-io** [substrate-developer-hub/substrate-node-template#90]
**Description**

I did manage to install the node and run it together with the web front-end maybe 5 days ago. But when I started all over again I can't get it compiled. I did to reinstall rust and de-brew dependency modules but all in vain. Also tried with rustc 1.46, restarted mac, reinstalled cmake, openssl...
Attached is the log with the whole installation procedure.
[subrtrate-install.log](https://github.com/substrate-developer-hub/substrate-node-template/files/5351338/subrtrate-install.log)

**Steps to Reproduce**

following step by step [Create Your First Substrate Chain](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup)

**Environment**
- Operating system: MacOS, Kernel Version: Darwin 18.2.0
- Template version/tag: v2.0.0
- Rust version (run `rustup show`):
```
Default host: x86_64-apple-darwin
rustup home:  /Users/mario/.rustup

installed toolchains

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain

stable-x86_64-apple-darwin (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```
**Logs, Errors or Screenshots**
```
...
   Compiling frame-support-procedural v2.0.0
   Compiling libp2p-core v0.22.1
error: failed to run custom build command for `node-template-runtime v2.0.0 (/Users/mario/projects/substrate-node-template/runtime)`

Caused by:
  process didn't exit successfully: `/Users/mario/projects/substrate-node-template/target/release/build/node-template-runtime-cae9ad6029c9f681/build-script-build` (exit code: 1)
  --- stdout
  Executing build command: "rustup" "run" "nightly" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/mario/projects/substrate-node-template/target/release/wbuild/node-template-runtime/Cargo.toml" "--color=always" "--release"

  --- stderr
      Updating crates.io index
   Downloading crates ...
    Downloaded getrandom v0.1.15
    Downloaded substrate-wasm-builder v2.0.0
```

**This error comes after random file and doesn't look connected with libp2p-core v0.22.1 in this case.
After continuing with compile it always breaks with following error:**

```
...     
     Compiling sp-wasm-interface v2.0.0
     Compiling sp-arithmetic v2.0.0
     Compiling finality-grandpa v0.12.3
  error[E0282]: type annotations needed
      --> /Users/mario/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Additional Information**

**Comment by Apollo50** [comment]
Hello. I have exactly the same problem.
I try to make first compile by guide and get this errors. It doesn't related of specific file. If i restart compiling i'll get this error again on another file.
I dont add log because its identical.

Operating system: Ubuntu 19.10

> 
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/eugene/.rustup

installed toolchains

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain

stable-x86_64-unknown-linux-gnu (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)
>

**Comment by benxiao** [comment]
Same here.

**Comment by kaichaosun** [comment]
Try this:
```shell
rustup uninstall nightly

rustup install nightly-2020-10-06

# find your nightly toolchain
rustup toolchain list

rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06-x86_64-unknown-linux-gnu
```

**Comment by Maar-io** [comment]
Thanks @kaichaosun 

it works for me on MacOS with your suggestion!!!

Last login: Thu Oct  8 19:40:40 on ttys001
~ $ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/mario/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2020-10-06-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)

~ $

**Comment by wheresaddie** [comment]
closing issue in lieu of patch #91 

please open again if you have further issues or submit a new PR. thanks all!

**Comment by NukeManDan** [comment]
It would be good to update the tutorials for this problem... as many are running into this following instructions on https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/

**Comment by bjwswang** [comment]
I faced the same issue today on ubuntu18.04.  The `WASM_BUILD_TOOLCHAIN` is hardcoded to `nightly-2020-10-05`.

**Comment by YusufSina** [comment]
Thanks, @kaichaosun 

After installing nightly-2020-10-06, I did

`$ rustup default nightly-2020-10-05-x86_64-pc-windows-msvc`

and built it again. 

built it successfully for windows

**Comment by Asamartino** [comment]
thank you @kaichaosun  and @YusufSina.  I was struggling to install it on Windows so I tried on Ubuntu (using a VM) and encountered the same problem. With your help it now works on both operating systems.

**Comment by playground** [comment]
I'm seeing a the issue.  Tried @kaichaosun suggestion but didn't work

Running Mac OS Big Sur

Default host: x86_64-apple-darwin
rustup home:  /Users/jeff/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-2020-10-05-x86_64-apple-darwin
nightly-2020-10-06-x86_64-apple-darwin
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)

**Comment by NukeManDan** [comment]
@playground what version of the node template are you using?

[v2.0.1](https://github.com/substrate-developer-hub/substrate-node-template/releases/tag/v2.0.1) is recommended to solve build issues.

To migrate, checkout/clone that tag/branch, and run in the working dir:
 ```shell
 rustup default stable
 make init
 cargo clean
 make build
 ```

**Comment by playground** [comment]
Thanks @NukeManDan, using node template v2.0.1 works.

Got both node server and client running, however when try to transfer fund it throwing this error

![image](https://user-images.githubusercontent.com/243495/105936541-e1001b80-6021-11eb-835c-1539fbb7326b.png)

**Comment by NukeManDan** [comment]
@playground we have a fixed frontend template, you can use the template from the [master branch](https://github.com/substrate-developer-hub/substrate-front-end-template) {clone it fresh, or checkout this branch} that just got the patch, or do a very simple manually update as described in [this issue](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/835)

**Comment by playground** [comment]
@NukeManDan actually I did try that but didn't seem to work, I will give it another try and let you know.

**Comment by Bobj2018** [comment]
> Thanks, @kaichaosun
> 
> After installing nightly-2020-10-06, I did
> 
> `$ rustup default nightly-2020-10-05-x86_64-pc-windows-msvc`
> 
> and built it again.
> 
> built it successfully for windows

I've been having problems with getting the project up and running on Ubuntu. This solved it. Thanks!

**Comment by NukeManDan** [comment]
You are using a _very very old version_ and this isn't going to work with any modern nodes! Please update `rust update` and set defaults to the defaluts (floating on the latest) and try again.

Try to clear your node template and frontend template, re-clone, and build again. 
@NtcWai - please open a new issue if you have more problems
