### ISSUE TITLE
 Compile error in building template:  type annotation needed

### ISSUE THREAD

**Issue by stetsonline** [substrate-developer-hub/substrate-node-template#94]
When trying to compile the substrate node template the following error occurred:

Compiling sp-runtime-interface v2.0.0
  error[E0282]: type annotations needed
      --> /Users/wardline/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
       |
  541  |                   let accuracy = P::ACCURACY.saturated_into();
       |                       ^^^^^^^^ consider giving `accuracy` a type
  ...
  1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Environment**

_MacOS 10.15 Imac Pro
Default host: x86_64-apple-darwin
rustup home:  /Users/wardline/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.47.0 (18bf6b4f0 2020-10-07)

I unsuccessfully tried cloning older versions of the template to see if this resolved the error.

**Comment by danforbes** [comment]
Can you please try this and close this Issue if it fixes your problem? https://github.com/substrate-developer-hub/substrate-node-template/issues/90#issuecomment-706041447

**Comment by wheresaddie** [comment]
try:

```
rustup install nightly-2020-10-06
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
cargo +nightly-2020-10-06 build --release
```

**Comment by wheresaddie** [comment]
oops @danforbes and I just replied in parallel .. 

please let us know if this fixes the issue

**Comment by stetsonline** [comment]
Yes!  That worked.  Thanks so much for the quick response.

**Comment by danforbes** [comment]
Glad to hear it! Hope you visit us in our technical chat and tell us all about what you're building :nerd_face: https://app.element.io/#/room/!HzySYSaIhtyWrwiwEV:matrix.org

**Comment by Swader** [comment]
At this point it might be useful to include a "downgrade.sh" script in `script` for easy access, and a wrapper for `cargo build --release` which on detected failure recommends trying that script and trying again.

**Comment by wheresaddie** [comment]
Unfortunately both ink! 2.1 + Cargo contract 0.6.2 aren't compatible with Substrate v2.0.0 atm, 
once we update all to ink! 3.0 the issue should go away (in theory)..

**Comment by danforbes** [comment]
Hopefully the inclusion of the `rust-toolchain` file is a proper, long-term fix https://github.com/substrate-developer-hub/substrate-node-template/blob/master/rust-toolchain

**Comment by tansaku** [comment]
I'm encountering a similar error for OSX 11.1 and rustc 1.49:

```

error[E0282]: type annotations needed
    --> /Users/samueljoseph/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1595 | / implement_fixed!(
1596 | |     FixedI64,
1597 | |     test_fixed_i64,
1598 | |     i64,
...    |
1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
1602 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /Users/samueljoseph/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1604 | / implement_fixed!(
1605 | |     FixedI128,
1606 | |     test_fixed_i128,
1607 | |     i128,
...    |
1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
1612 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /Users/samueljoseph/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1614 | / implement_fixed!(
1615 | |     FixedU128,
1616 | |     test_fixed_u128,
1617 | |     u128,
...    |
1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
1622 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

   Compiling zstd v0.5.3+zstd.1.4.5
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0282`.
error: could not compile `sp-arithmetic`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [build] Error 101
```

I tried https://github.com/substrate-developer-hub/substrate-node-template/issues/94#issuecomment-708548657 but it didn't help :-(

**Comment by tansaku** [comment]
ah fixed with https://stackoverflow.com/a/65756888/316729
