### ISSUE TITLE
Docker Script is Broken

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/substrate-node-template#95]
The Docker run script https://github.com/substrate-developer-hub/substrate-node-template/blob/master/scripts/docker_run.sh is suffering from a problem with the Rust nightly https://github.com/substrate-developer-hub/substrate-node-template/issues/90. It should use the nightly specified by the `rust-toolchain` file.

As reported by @anhcao142 https://github.com/substrate-developer-hub/substrate-node-template/issues/85#issuecomment-710107030

**Comment by TriplEight** [comment]
Your [toolchain file](https://github.com/substrate-developer-hub/substrate-node-template/blob/master/rust-toolchain) should not be newer than `docker run -it paritytech/ci-linux:production rustc +nightly --version`. That image is [tested](https://github.com/paritytech/scripts/blob/master/.gitlab-ci.yml#L234) to compile substrate every night, with the latest Rust versions and pushed only if the test is green. Ideally, it should match. So basically, you will need that file to return to an older version, since the newest possible is already in place.

**Comment by danforbes** [comment]
@TriplEight I updated the toolchain file to `nightly-2020-09-20`, which is what I found by running the command you specified, but I'm still getting more or less the same error.

```sh
     Compiling substrate-wasm-builder v2.0.1
     Compiling wasm-build-runner-impl v1.0.0 (/var/www/node-template/target/release/wbuild-runner/node-template-runtime1437524645330841452)
      Finished release [optimized] target(s) in 3m 36s
       Running `/var/www/node-template/target/release/wbuild-runner/node-template-runtime1437524645330841452/target/x86_64-unknown-linux-gnu/release/wasm-build-runner-impl`
  Rust WASM toolchain not installed, please install it!

  Further error information:
  ------------------------------------------------------------
     Compiling wasm-test v1.0.0 (/tmp/.tmpZIy6bF)
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `wasm-test`

  To learn more, run the command again with --verbose.
  ------------------------------------------------------------

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by TriplEight** [comment]
@danforbes do not forget to `docker pull paritytech/ci-linux:production` to update your local image, it's newer.
Also, the image has two toolchains, stable and nightly, you should mention both in `rust-toolchain` if you want to keep it.
i.e.
```
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
```

**Comment by TriplEight** [comment]
Or, with the current stable and latest working nightly:
```
stable-x86_64-unknown-linux-gnu
nightly-2020-10-05
```
