### ISSUE TITLE
Adding utils scripts for node-template

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-node-template#96]
The reason is that I think:
- "Renaming the Project Name" is a common feature that will be used. I also have that struggle before. Will be good to have a script to do that.
- "Adding a Pallet" script, I am struggling with this. The pro side is it helps ppl easily add a default simple pallet. But it also hides the complexity that if they need further configuration, as they do need to do it at different places - runtime/lib.rs for more configurable trait, chain_spec for genesis config, etc.

And I don't mind it as javascript as well (this also make it cross-platform). We just need to document it well the env required and instructions to run these scripts.

So I open this issue and want to discuss this with you all @danforbes  @riusricardo @wheresaddie (if we all feel yes, I also want to get some comments from 1-2 core-devs about this)

A question arise on how to do this automatically for release in future: I am thinking we may need a simple release script to grab whatever latest substrate/substrate-node-template content, and then pulling from another repo of these utils scripts and push to devhub/node-template repo for release.

Ref:
- https://github.com/danforbes/substrate-devhub-utils

**Comment by danforbes** [comment]
I created those scripts because I clearly believe they have utility, but I would propose that we include them in _this_ repo in particular. I would prefer to keep this repo in particular _very_ focused on the Node Template and little else.

**Comment by danforbes** [comment]
I think it would be really cool to create a CLI tool to help with renaming, scaffolding and more. here are some existing tools for inspiration
https://github.com/clearloop/sup (Substrate community package manager)
https://cli.angular.io/ (CLI for Angular front-end framework)
https://yeoman.io/learning/ (generic scaffolding tool)

**Comment by danforbes** [comment]
More inspo from Will
https://github.com/tendermint/starport (Cosmos/Tendermint solution)
https://github.com/near/create-near-app (Near solution)

**Comment by wheresaddie** [comment]
yes, I agree with Dan about setting up some CLI scripts for this, imo we esp need a simple release script to grab whatever latest substrate/substrate-node-template content needs changes, pulling from another repo of these utils scripts, pushing to devhub/node-template repo for immediate release ..

**Comment by jimmychu0807** [comment]
Will make this a todo item in my list.

**Comment by jimmychu0807** [comment]
Closing this, as I am not sure if people still complain about renaming the `node-template` node, the runtime, and the pallet.
