### ISSUE TITLE
How to add pallet-identity

### ISSUE THREAD

**Issue by master-davidlee** [substrate-developer-hub/substrate-node-template#97]
**Question**
How to add pallet-identity to node-template?
_Please include information such as the following: is your question to clarify an existing resource
or are you asking about something new? what are you trying to accomplish? where have you looked for
answers?_

**Comment by danforbes** [comment]
Are you working on this GitCoin challenge? https://gitcoin.co/issue/Polkadot-Network/hello-world-by-polkadot/10/100023936 What have you tried so far? Have you completed this tutorial? https://substrate.dev/docs/en/tutorials/add-a-pallet/

**Comment by master-davidlee** [comment]
I have solve it.
